---
alias: Sonos - Playlist - 1170 SEN
id: 1170_SEN
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "1170 SEN"
  - platform: webhook
    webhook_id: sonos_1170_SEN
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "1170 SEN"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
