---
alias: Sonos - Playlist - 1170 SEN
description: Play 1170 SEN on Sonos
id: 1170_SEN
trigger:
  - platform: webhook
    webhook_id: sonos_1170_SEN
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "1170 SEN"
