---
alias: Sonos - Playlist - 1-Playlist
id: 1_Playlist
trigger:
  - platform: webhook
    webhook_id: sonos_1_Playlist
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "1-Playlist"
