---
alias: Sonos - Playlist - ABC News
id: ABC_News
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "ABC News"
  - platform: webhook
    webhook_id: sonos_ABC_News
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "ABC News"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
