---
alias: Sonos - Playlist - ABC New England North West
description: Play ABC New England North West on Sonosid: ABC_New_England_North_West
trigger:
  - platform: webhook
    webhook_id: sonos_ABC_New_England_North_West
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "ABC New England North West"
