---
alias: Sonos - Playlist - ABC Sport
id: ABC_Sport
trigger:
  - platform: webhook
    webhook_id: sonos_ABC_Sport
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "ABC Sport"
