---
alias: Sonos - Playlist - ABC Radio National (Sydney, NSW)
id: ABC_Radio_National__Sydney__NSW
trigger:
  - platform: webhook
    webhook_id: sonos_ABC_Radio_National__Sydney__NSW
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "ABC Radio National (Sydney, NSW)"
