---
alias: Sonos - Playlist - ABC News
id: ABC_News
trigger:
  - platform: webhook
    webhook_id: sonos_ABC_News
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "ABC News"
