---
alias: Sonos - Playlist - ABC New England North West
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "ABC New England North West"
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "ABC New England North West"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
