---
alias: Sonos - Playlist - ABC Sport
id: ABC_Sport
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "ABC Sport"
  - platform: webhook
    webhook_id: sonos_ABC_Sport
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "ABC Sport"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
