---
alias: Sonos - Playlist - ABC Radio National (Sydney, NSW)
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "ABC Radio National (Sydney, NSW)"
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "ABC Radio National (Sydney, NSW)"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
