---
alias: Sonos - Playlist - ABC Radio National (Sydney, NSW)
description: Play ABC Radio National (Sydney, NSW) on Sonos
id: ABC_Radio_National_Sydney_NSW
trigger:
  - platform: webhook
    webhook_id: sonos_ABC_Radio_National_Sydney_NSW
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "ABC Radio National (Sydney, NSW)"
