---
alias: Sonos - Playlist - Absolute Radio 90s
id: Absolute_Radio_90s
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "Absolute Radio 90s"
  - platform: webhook
    webhook_id: sonos_Absolute_Radio_90s
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Absolute Radio 90s"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
