---
alias: Sonos - Playlist - Absolute Radio 20s
id: Absolute_Radio_20s
trigger:
  - platform: webhook
    webhook_id: sonos_Absolute_Radio_20s
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Absolute Radio 20s"
