---
alias: Sonos - Playlist - Absolute Radio 90s
description: Play Absolute Radio 90s on Sonosid: Absolute_Radio_90s
trigger:
  - platform: webhook
    webhook_id: sonos_Absolute_Radio_90s
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Absolute Radio 90s"
