---
alias: Sonos - Playlist - Absolute Radio 00s
id: Absolute_Radio_00s
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "Absolute Radio 00s"
  - platform: webhook
    webhook_id: sonos_Absolute_Radio_00s
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Absolute Radio 00s"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
