---
alias: Sonos - Playlist - Absolute Radio 00s
description: Play Absolute Radio 00s on Sonosid: Absolute_Radio_00s
trigger:
  - platform: webhook
    webhook_id: sonos_Absolute_Radio_00s
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Absolute Radio 00s"
