---
alias: Sonos - Playlist - Absolute Radio UK (AAC)
id: Absolute_Radio_UK__AAC
trigger:
  - platform: webhook
    webhook_id: sonos_Absolute_Radio_UK__AAC
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Absolute Radio UK (AAC)"
