---
alias: Sonos - Playlist - Absolute Radio Classic Rock
id: 75bf0156-9acf-4dbf-89a1-a490eafafc6d
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "Absolute Radio Classic Rock"
  - platform: webhook
    webhook_id: sonos_Absolute_Radio_Classic_Rock
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Absolute Radio Classic Rock"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
