---
alias: Sonos - Playlist - Absolute Radio 80s
description: Play Absolute Radio 80s on Sonos
id: Absolute_Radio_80s
trigger:
  - platform: webhook
    webhook_id: sonos_Absolute_Radio_80s
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Absolute Radio 80s"
