---
alias: Sonos - Playlist - Absolute Radio Classic Rock
description: Play Absolute Radio Classic Rock on Sonos
id: Absolute_Radio_Classic_Rock
trigger:
  - platform: webhook
    webhook_id: sonos_Absolute_Radio_Classic_Rock
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Absolute Radio Classic Rock"
