---
alias: Sonos - Playlist - Absolute Radio 80s
id: Absolute_Radio_80s
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "Absolute Radio 80s"
  - platform: webhook
    webhook_id: sonos_Absolute_Radio_80s
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Absolute Radio 80s"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
