---
alias: Sonos - Playlist - BBC Radio 1
id: 5c394b10-1f27-4145-b438-344436fec6c8
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "BBC Radio 1"
  - platform: webhook
    webhook_id: sonos_BBC_Radio_1
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "BBC Radio 1"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
