---
alias: Sonos - Playlist - BBC Radio 5 live
id: 2c921b60-ca12-429a-b5b2-2f5c33c63ac7
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "BBC Radio 5 live"
  - platform: webhook
    webhook_id: sonos_BBC_Radio_5_live
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "BBC Radio 5 live"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
