---
alias: Sonos - Playlist - BBC Radio 1
description: Play BBC Radio 1 on Sonos
id: BBC_Radio_1
trigger:
  - platform: webhook
    webhook_id: sonos_BBC_Radio_1
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "BBC Radio 1"
