---
alias: Sonos - Playlist - BBC Radio 6 Music
id: BBC_Radio_6_Music
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "BBC Radio 6 Music"
  - platform: webhook
    webhook_id: sonos_BBC_Radio_6_Music
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "BBC Radio 6 Music"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
