---
alias: Sonos - Playlist - BBC World Service News
description: Play BBC World Service News on Sonosid: BBC_World_Service_News
trigger:
  - platform: webhook
    webhook_id: sonos_BBC_World_Service_News
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "BBC World Service News"
