---
alias: Sonos - Playlist - BBC Radio 2
id: BBC_Radio_2
trigger:
  - platform: webhook
    webhook_id: sonos_BBC_Radio_2
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "BBC Radio 2"
