---
alias: Sonos - Playlist - BBC Radio 5 live
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "BBC Radio 5 live"
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "BBC Radio 5 live"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
