---
alias: Sonos - Playlist - BBC Radio 5 live
description: Play BBC Radio 5 live on Sonosid: BBC_Radio_5_live
trigger:
  - platform: webhook
    webhook_id: sonos_BBC_Radio_5_live
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "BBC Radio 5 live"
