---
alias: Sonos - Playlist - CNN International
description: Play CNN International on Sonos
id: CNN_International
trigger:
  - platform: webhook
    webhook_id: sonos_CNN_International
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "CNN International"
