---
alias: Sonos - Playlist - CNN International
id: a78a4c85-01f4-4e94-a1d9-6de5c3f95b00
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "CNN International"
  - platform: webhook
    webhook_id: sonos_CNN_International
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "CNN International"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
