---
alias: Sonos - Playlist - COVID-19 Social Distancing Sucks
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "COVID-19 Social Distancing Sucks"
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "COVID-19 Social Distancing Sucks"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
