---
alias: Sonos - Playlist - COVID-19 Social Distancing Sucks
description: Play COVID-19 Social Distancing Sucks on Sonosid: COVID_19_Social_Distancing_Sucks
trigger:
  - platform: webhook
    webhook_id: sonos_COVID_19_Social_Distancing_Sucks
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "COVID-19 Social Distancing Sucks"
