---
alias: Sonos - Playlist - COVID-19 Social Distancing Sucks
id: abe14297-c034-413a-8a16-5489c8f35f5a
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "COVID-19 Social Distancing Sucks"
  - platform: webhook
    webhook_id: sonos_COVID_19_Social_Distancing_Sucks
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "COVID-19 Social Distancing Sucks"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
