---
alias: Sonos - Playlist - ESPN Radio
description: Play ESPN Radio on Sonosid: ESPN_Radio
trigger:
  - platform: webhook
    webhook_id: sonos_ESPN_Radio
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "ESPN Radio"
