---
alias: Sonos - Playlist - GOLD 104.3
description: Play GOLD 104.3 on Sonosid: GOLD_104_3
trigger:
  - platform: webhook
    webhook_id: sonos_GOLD_104_3
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "GOLD 104.3"
