---
alias: Sonos - Playlist - MSNBC
id: MSNBC
trigger:
  - platform: webhook
    webhook_id: sonos_MSNBC
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "MSNBC"
