---
alias: Sonos - Playlist - MSNBC
id: ed7046bc-9bd3-4c55-8bf7-2dacef5f2316
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "MSNBC"
  - platform: webhook
    webhook_id: sonos_MSNBC
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "MSNBC"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
