---
alias: Sonos - Playlist - Nova Throwbacks
id: 16364cd3-65a7-43b0-8890-f9185b379cc2
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "Nova Throwbacks"
  - platform: webhook
    webhook_id: sonos_Nova_Throwbacks
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Nova Throwbacks"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
