---
alias: Sonos - Playlist - Nova 96.9
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "Nova 96.9"
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Nova 96.9"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
