---
alias: Sonos - Playlist - Nova 90s
id: Nova_90s
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "Nova 90s"
  - platform: webhook
    webhook_id: sonos_Nova_90s
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Nova 90s"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
