---
alias: Sonos - Playlist - Playlists
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "Playlists"
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Playlists"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
