---
alias: Sonos - Playlist - Playlists
description: Play Playlists on Sonos
id: Playlists
trigger:
  - platform: webhook
    webhook_id: sonos_Playlists
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Playlists"
