---
alias: Sonos - Playlist - Radio X
id: Radio_X
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "Radio X"
  - platform: webhook
    webhook_id: sonos_Radio_X
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Radio X"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
