---
alias: Sonos - Playlist - Radio X
id: Radio_X
trigger:
  - platform: webhook
    webhook_id: sonos_Radio_X
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Radio X"
