---
alias: Sonos - Playlist - Sky News Radio
id: Sky_News_Radio
trigger:
  - platform: webhook
    webhook_id: sonos_Sky_News_Radio
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Sky News Radio"
