---
alias: Sonos - Playlist - Sky News Radio
id: Sky_News_Radio
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "Sky News Radio"
  - platform: webhook
    webhook_id: sonos_Sky_News_Radio
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Sky News Radio"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
