---
alias: Sonos - Playlist - Tamworth's 88.9FM
description: Play Tamworth's 88.9FM on Sonos
id: Tamworth_s_88_9FM
trigger:
  - platform: webhook
    webhook_id: sonos_Tamworth_s_88_9FM
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Tamworth's 88.9FM"
