---
alias: Sonos - Playlist - The Edge 94.2 (Top 40 & Pop Music)
description: Play The Edge 94.2 (Top 40 & Pop Music) on Sonos
id: The_Edge_94_2_Top_40_Pop_Music
trigger:
  - platform: webhook
    webhook_id: sonos_The_Edge_94_2_Top_40_Pop_Music
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "The Edge 94.2 (Top 40 & Pop Music)"
