---
alias: Sonos - Playlist - Triple M 104.9 Sydney
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "Triple M 104.9 Sydney"
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Triple M 104.9 Sydney"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
