---
alias: Sonos - Playlist - triple j (New South Wales)
id: triple_j_New_South_Wales
trigger:
  - platform: webhook
    webhook_id: sonos_triple_j_New_South_Wales
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "triple j (New South Wales)"
