---
alias: Sonos - Playlist - Triple M Hard n Heavy (Sydney)
id: Triple_M_Hard_n_Heavy_Sydney
trigger:
  - platform: webhook
    webhook_id: sonos_Triple_M_Hard_n_Heavy_Sydney
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Triple M Hard n Heavy (Sydney)"
