---
alias: Sonos - Playlist - Triple M Hard n Heavy (Sydney)
id: Triple_M_Hard_n_Heavy__Sydney
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "Triple M Hard n Heavy (Sydney)"
  - platform: webhook
    webhook_id: sonos_Triple_M_Hard_n_Heavy__Sydney
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Triple M Hard n Heavy (Sydney)"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
