---
alias: Sonos - Playlist - Triple M 90s (Sydney)
id: Triple_M_90s_Sydney
trigger:
  - platform: webhook
    webhook_id: sonos_Triple_M_90s_Sydney
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Triple M 90s (Sydney)"
