---
alias: Sonos - Playlist - Triple M 105.1 Melbourne
description: Play Triple M 105.1 Melbourne on Sonosid: Triple_M_105_1_Melbourne
trigger:
  - platform: webhook
    webhook_id: sonos_Triple_M_105_1_Melbourne
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Triple M 105.1 Melbourne"
