---
alias: Sonos - Playlist - Triple M Classic Rock Digital (Sydney)
description: Play Triple M Classic Rock Digital (Sydney) on Sonos
id: Triple_M_Classic_Rock_Digital_Sydney
trigger:
  - platform: webhook
    webhook_id: sonos_Triple_M_Classic_Rock_Digital_Sydney
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Triple M Classic Rock Digital (Sydney)"
