---
alias: Sonos - Playlist - Triple M 105.1 Melbourne
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "Triple M 105.1 Melbourne"
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Triple M 105.1 Melbourne"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
