---
alias: Sonos - Playlist - Virgin Radio UK
id: Virgin_Radio_UK
trigger:
  - platform: state
    entity_id: input_select.sonosplaylist
    to: "Virgin Radio UK"
  - platform: webhook
    webhook_id: sonos_Virgin_Radio_UK
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Virgin Radio UK"
  - service: input_select.select_option
    data:
      entity_id: input_select.sonosplaylist
      option: "-- Select --"
