---
alias: Sonos - Playlist - Virgin Radio Chilled UK
id: Virgin_Radio_Chilled_UK
trigger:
  - platform: webhook
    webhook_id: sonos_Virgin_Radio_Chilled_UK
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Virgin Radio Chilled UK"
