---
alias: Sonos - Playlist - Virgin Radio UK
description: Play Virgin Radio UK on Sonos
id: Virgin_Radio_UK
trigger:
  - platform: webhook
    webhook_id: sonos_Virgin_Radio_UK
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Virgin Radio UK"
