---
alias: Sonos - Playlist - Virgin Radio Anthems UK
description: Play Virgin Radio Anthems UK on Sonosid: Virgin_Radio_Anthems_UK
trigger:
  - platform: webhook
    webhook_id: sonos_Virgin_Radio_Anthems_UK
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Virgin Radio Anthems UK"
