---
alias: Sonos - Playlist - Virgin Radio Groove UK
description: Play Virgin Radio Groove UK on Sonos
id: Virgin_Radio_Groove_UK
trigger:
  - platform: webhook
    webhook_id: sonos_Virgin_Radio_Groove_UK
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Virgin Radio Groove UK"
