---
homeassistant:
  # name: !secret ha_name
  # latitude: !secret zone_home_latitude
  # longitude: !secret zone_home_longitude
  # elevation: 430
  # unit_system: metric
  # time_zone: !secret ha_timezone
  customize: !include ../customize.yaml
  # external_url: !secret external_url
  # external_url: !secret internal_url
  # whitelist_external_dirs:
  #   - /config
  # auth_providers:
  #   - type: trusted_networks
  #     trusted_networks:
  #       - 127.0.0.1
  #       - ::1
  #       - 192.168.1.0/24
  #   - type: homeassistant