---
homeassistant:
  customize_glob:
    package.node_anchors:
      customize: &customize
        package: "monitordocker"
    "*monitordocker*":
      <<: *customize

monitor_docker:
  - name: TBSH01_monitordocker
    url: tcp://192.168.1.20:2375
    rename:
      thirsty_wiles: "glances"

  - name: TBSH03_monitordocker
    url: tcp://192.168.1.65:2375

  - name: vmTBSH01_monitordocker
    url: tcp://192.168.1.61:2375
    rename:
      nice_johnson: "glances"

  - name: vmTBSH02_monitordocker
    url: tcp://192.168.1.62:2375
    rename:
      suspicious_golick: "glances"

  - name: vmTBSH03_monitordocker
    url: tcp://192.168.1.63:2375
    rename:
      ha-dockermon: "HA Dockermon"
