---
homeassistant:
  customize_glob:
    package.node_anchors:
      customize: &customize
        package: "monitordocker"
    "*monitordocker*":
      <<: *customize

monitor_docker:
  - name: TBSH1_monitordocker
    url: tcp://192.168.1.91:2375
    scan_interval: 60
    monitored_conditions:
      - allinone

  - name: TBSH03_monitordocker
    url: tcp://192.168.1.65:2375
    scan_interval: 60
    monitored_conditions:
      - allinone

  - name: PI4SRV_monitordocker
    url: tcp://192.168.1.64:2375
    scan_interval: 60
    monitored_conditions:
      - allinone