---
sensor:
  - name: "Tamworth Fuel Average ULP95"
    unique_id: sensor.fuel_tamworth_average_ulp95
    unit_of_measurement: c/L
    icon: mdi:gas-station
    state: >
      {%- set sensors = states|selectattr('entity_id','search','_ulp95') | map(attribute='entity_id')| list %}
      {{ expand(sensors)  | rejectattr('state', 'in', ['unknown','unavailable']) | map(attribute='state')  | map('float', 0) | average | round(2) }}
    availability: >
      {%- set sensors = states|selectattr('entity_id','search','_ulp95')  | map(attribute='entity_id')| list %}
      {{ expand(sensors) | rejectattr('state', 'in', ['unknown','unavailable']) | list | count > 0}}
    attributes:
      max: >
        {%- set sensors = states|selectattr('entity_id','search','_ulp95')  | map(attribute='entity_id')| list %}
        {{ expand(sensors)  | rejectattr('state', 'in', ['unknown','unavailable']) | map(attribute='state')  | map('float', 0) | max | round(2) }}
      min: >
        {%- set sensors = states|selectattr('entity_id','search','_ulp95') | map(attribute='entity_id')| list %}
        {{ expand(sensors) | rejectattr('state', 'in', ['unknown','unavailable']) | map(attribute='state')  | map('float', 0) | min | round(2) }}
