- id: '1615679580065'
  alias: Certificate Expiration
  description: ''
  use_blueprint:
    path: bkbilly/certificate-expiration.yaml
    input:
      time_input: '15:00:00'
      certificate_input: sensor.cert_expiry_timestamp_tbsmartho_me
      notify_device: 7ec71e5518f311eb9636fd68a1e47a67
- id: '1615967841411'
  alias: New Automation
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:35:00
  condition: []
  action:
  - scene: scene.all_lights_work
  mode: single
