---
id: logs_counter_reset
alias: Logs - Counters reset on start
trigger:
  platform: homeassistant
  event: start
action:
  - service: counter.reset
    entity_id: counter.logs_warning_counter
  - service: counter.reset
    entity_id: counter.logs_critical_counter
  - service: counter.reset
    entity_id: counter.logs_error_counter