---
id: "pyscript_getdata_hourly"
alias: "PyScript, GetData: Hourly"
description: "PyScript, GetData: Hourly"
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: "/1"
condition: []
action:
  - service: pyscript.getdata_bomforecast
    data:
      icon: "mdi:weather"
mode: single
