set_auto_mode:
  description: Set the fan in auto mode.
  fields:
    entity_id:
      description: Name(s) of the entities to enable/disable auto mode
      example: "fan.living_room"
    auto_mode:
      description: Auto mode status
      example: true

set_speed:
  description: Set the exact speed of the fan.
  fields:
    entity_id:
      description: Name(s) of the entities to set the speed for
      example: "fan.living_room"
    dyson_speed:
      description: Speed
      example: 1
