---
alias: Webhook - Office Lamp Toggle
description: ""
initial_state: true
trigger:
  - platform: webhook
    webhook_id: office_lamp_toggle
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: "OfficeLightsOn"
action:
  - entity_id: light.office_lamp
    service: light.toggle
    data: {}
