---
alias: HACS - Updates Available
id: hacs_updates
mode: single

trigger:
  - platform: state
    entity_id: sensor.hacs

condition:
  - condition: numeric_state
    entity_id: sensor.hacs
    above: 0

action:
  - service: persistent_notification.create
    data_template:
      title: HACS - Updates Available
      message: >-
        {% for repo in state_attr('sensor.hacs', 'repositories') %}
          *{{ repo.display_name }}* _{{ repo["installed_version"] }}_ -> _{{ repo["available_version"] }}_
        {% endfor %}
  - service: notify.slack
    data_template:
      message: ""
      target: "#tbsmarthome"
      data:
        blocks:
          - type: section
            text:
              type: mrkdwn
              text: "*HACS - Updates Available*"
          - type: section
            text:
              type: mrkdwn
              text: >-
                {% for repo in state_attr('sensor.hacs', 'repositories') %}
                  *{{ repo.display_name }}* _{{ repo["installed_version"] }}_ -> _{{ repo["available_version"] }}_
                {% endfor %}
