---
alias: HACS - New Repository Added
id: hacs_newrepo
trigger:
  - platform: event
    event_type: hacs/repository
    event_data:
      action: registration
condition:
  - condition: template
    value_template: "{{ trigger.event.data.repository is defined }}"
action:
  - service: persistent_notification.create
    data_template:
      title: "HACS - New Repository Added"
      message: >-
        {% set repo = trigger.event.data.repository %}
        {% set id = trigger.event.data.repository_id %}
        [{{ repo }}](/hacs/repository/{{ id }})
        was just added to HACS.
  - service: notify.slack
    data_template:
      message: "HACS - New Repository Added"
      target: "#tbsmarthome"
      data:
        blocks:
          - type: section
            text:
              type: mrkdwn
              text: "*HACS - New Repository Added*"
          - type: section
            text:
              type: mrkdwn
              text: >-
                {% set repo = trigger.event.data.repository %}
                {% set id = trigger.event.data.repository_id %}
                [{{ repo }}](/hacs/repository/{{ id }})
                was just added to HACS.
