---
id: "runyamllint"
alias: Admin - Run YAMLLint
description: Generate YAMLLint file every night
trigger:
  - platform: time_pattern
    hours: "1"
    minutes: "30"
condition: []
action:
  - service: shell_command.run_yamllint
mode: single
