---
id: "influx2entity_internetdownload365day"
alias: "InfluxDB to Entity: 365 Day Internet Download"
description: "InfluxDB to Entity: 365 Day Internet Download"
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: "/1"
condition: []
action:
  - service: pyscript.influxdb_query_to_entity
    data:
      database: homeassistant
      query: >-
        SELECT max("value") AS "value"
        FROM "homeassistant"."autogen"."Mbit/s"
        WHERE time >= now() - 365d AND "entity_id"='speedtest_download'
        GROUP BY time(1d) FILL(linear) tz('Australia/Sydney')
      key_field_name: time
      value_field_name: value
      entity_id: sensor.archive_internet_download_max_365day
      unit_of_measurement: mbit/s
      friendly_name: Internet Download Speed - Max Speed - 365 Day
      icon: "mdi:download-network"
  - service: pyscript.influxdb_query_to_entity
    data:
      database: homeassistant
      query: >-
        SELECT min("value") AS "value"
        FROM "homeassistant"."autogen"."Mbit/s"
        WHERE time >= now() - 365d AND "entity_id"='speedtest_download'
        GROUP BY time(1d) FILL(linear) tz('Australia/Sydney')
      key_field_name: time
      value_field_name: value
      entity_id: sensor.archive_internet_download_min_365day
      unit_of_measurement: mbit/s
      friendly_name: Internet Download Speed - Min Speed - 365 Day
      icon: "mdi:download-network"
  - service: pyscript.influxdb_query_to_entity
    data:
      database: homeassistant
      query: >-
        SELECT mean("value") AS "value"
        FROM "homeassistant"."autogen"."Mbit/s"
        WHERE time >= now() - 365d AND "entity_id"='speedtest_download'
        GROUP BY time(1d) FILL(linear) tz('Australia/Sydney')
      key_field_name: time
      value_field_name: value
      entity_id: sensor.archive_internet_download_mean_365day
      unit_of_measurement: mbit/s
      friendly_name: Internet Download Speed - Mean Speed - 365 Day
      icon: "mdi:download-network"
mode: single
