---
id: "influx2entity_internetupload365day"
alias: "InfluxDB to Entity: 365 Day Internet Upload"
description: "InfluxDB to Entity: 365 Day Internet Upload"
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: "/1"
condition: []
action:
  - service: pyscript.influxdb_query_to_entity
    data:
      database: homeassistant
      query: >-
        SELECT max("value") AS "value"
        FROM "homeassistant"."autogen"."Mbit/s"
        WHERE time >= now() - 365d AND "entity_id"='speedtest_upload'
        GROUP BY time(1d) FILL(linear) tz('Australia/Sydney')
      key_field_name: time
      value_field_name: value
      entity_id: sensor.archive_internet_upload_max_365day
      unit_of_measurement: mbit/s
      friendly_name: Internet Upload Speed - Max Speed - 365 Day
      icon: "mdi:upload-network"
  - service: pyscript.influxdb_query_to_entity
    data:
      database: homeassistant
      query: >-
        SELECT min("value") AS "value"
        FROM "homeassistant"."autogen"."Mbit/s"
        WHERE time >= now() - 365d AND "entity_id"='speedtest_upload'
        GROUP BY time(1d) FILL(linear) tz('Australia/Sydney')
      key_field_name: time
      value_field_name: value
      entity_id: sensor.archive_internet_upload_min_365day
      unit_of_measurement: mbit/s
      friendly_name: Internet Upload Speed - Min Speed - 365 Day
      icon: "mdi:upload-network"
  - service: pyscript.influxdb_query_to_entity
    data:
      database: homeassistant
      query: >-
        SELECT mean("value") AS "value"
        FROM "homeassistant"."autogen"."Mbit/s"
        WHERE time >= now() - 365d AND "entity_id"='speedtest_upload'
        GROUP BY time(1d) FILL(linear) tz('Australia/Sydney')
      key_field_name: time
      value_field_name: value
      entity_id: sensor.archive_internet_upload_mean_365day
      unit_of_measurement: mbit/s
      friendly_name: Internet Upload Speed - Mean Speed - 365 Day
      icon: "mdi:upload-network"
mode: single
