---
id: "influx2sensor_30dayrain"
alias: "InfluxDB to Sensor: 30 Day Rain"
description: "InfluxDB to Sensor: 30 Day Rain"
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: "/1"
condition: []
action:
  - service: pyscript.influxdb_query_to_sensor
    data:
      database: homeassistant
      query: >-
        SELECT max("value") FROM "homeassistant"."autogen"."mm"
        WHERE time >= now() - 30d AND "entity_id"='weather_outside_rain_day'
        GROUP BY time(1d) FILL(null) tz('Australia/Sydney')
      key_field_name: time
      value_field_name: max
      sensor: sensor.archive_homerain_30day
      unit_of_measurement: mm
      friendly_name: Home - 30 Day - Rain
      icon: "mdi:water"
mode: single
