---
id: "influx2entity_30daymintemp"
alias: "InfluxDB to Entity: 30 Day Min Temp"
description: "InfluxDB to Entity: 30 Day Min Temp"
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: "/1"
condition: []
action:
  - service: pyscript.influxdb_query_to_entity
    data:
      database: homeassistant
      query: >-
        SELECT min("value") FROM "homeassistant"."autogen"."°C" WHERE time >=
        now() - 30d AND "entity_id"='weather_outside_temperature' GROUP BY
        time(1d) FILL(null) tz('Australia/Sydney')
      key_field_name: time
      value_field_name: min
      entity_id: sensor.archive_homeoutsidetemp_min_30day
      unit_of_measurement: °C
      friendly_name: Home - 30 Day - Min Temp
      icon: "mdi:thermometer"
mode: single
