---
id: "influx2entity_365daymintempbom"
alias: "InfluxDB to Entity: 365 Day Min Temp BOM"
description: "InfluxDB to Entity: 365 Day Min Temp BOM"
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: "/1"
condition: []
action:
  - service: pyscript.influxdb_query_to_entity
    data:
      database: homeassistant
      query: >-
        SELECT min("value") FROM "homeassistant"."autogen"."°C"
        WHERE time >= now() - 365d
        AND ("entity_id"='tamworth_airport_temperature' OR "entity_id"='bom_tamworth_air_temp_c' OR "entity_id"='tamworth_airport_temp')
        GROUP BY time(1d,9h) FILL(previous) tz('Australia/Sydney')
      key_field_name: time
      value_field_name: min
      entity_id: sensor.archive_bomtemp_min_365day
      unit_of_measurement: °C
      friendly_name: BOM - 365 Day - Min Temp
      icon: "mdi:thermometer"
mode: single
