---
id: "influx2entity_365dayrainbom"
alias: "InfluxDB to Entity: 365 Day Rain BOM"
description: "InfluxDB to Entity: 365 Day Rain BOM"
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: "/1"
condition: []
action:
  - service: pyscript.influxdb_query_to_entity
    data:
      database: homeassistant
      query: >-
        SELECT last("value") FROM "homeassistant"."autogen"."mm"
        WHERE time >= now() - 365d AND ("entity_id"='bom_rain_today' OR "entity_id"='bom_tamworth_rain_today' or "entity_id"='tamworth_airport_rain_since_9am')
        GROUP BY time(1d,9h) FILL(null) tz('Australia/Sydney')
      key_field_name: time
      value_field_name: last
      entity_id: sensor.archive_bomrain_365day
      unit_of_measurement: mm
      friendly_name: BOM - 365 Day - Rain
      icon: "mdi:water"
mode: single
