---
id: "influx2sensor_365daymintemp"
alias: "InfluxDB to Sensor: 365 Day Min Temp"
description: "InfluxDB to Sensor: 365 Day Min Temp"
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: "/1"
condition: []
action:
  - service: pyscript.influxdb_query_to_sensor
    data:
      database: homeassistant
      query: >-
        SELECT min("value") FROM "homeassistant"."autogen"."°C"
        WHERE time >= now() - 365d
        AND ("entity_id"='netatmo_brisbane_street_outdoor_temperature' or "entity_id"='weather_outside_temperature')
        GROUP BY time(1d) FILL(null) tz('Australia/Sydney')
      key_field_name: time
      value_field_name: min
      sensor: sensor.archive_homeoutsidetemp_min_365day
      unit_of_measurement: °C
      friendly_name: Home - 365 Day - Min Temp
      icon: "mdi:thermometer"
mode: single
