---
id: "influx2entity_365dayrain"
alias: "InfluxDB to Entity: 365 Day Rain"
description: "InfluxDB to Entity: 365 Day Rain"
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: "/1"
condition: []
action:
  - service: pyscript.influxdb_query_to_entity
    data:
      database: homeassistant
      query: >-
        SELECT max("value") FROM "homeassistant"."autogen"."mm"
        WHERE time >= now() - 365d AND ("entity_id"='netatmo_rain_sum_rain_24' OR "entity_id"='netatmo_brisbane_street_rain_sum_rain_24' or "entity_id"='weather_outside_rain_day')
        GROUP BY time(1d) FILL(null) tz('Australia/Sydney')
      key_field_name: time
      value_field_name: max
      entity_id: sensor.archive_homerain_365day
      unit_of_measurement: mm
      friendly_name: Home - 365 Day - Rain
      icon: "mdi:water"
mode: single
