---
trigger:
  - platform: time_pattern
    minutes: "/5"
sensor:
  - name: "Covid NSW Fully Vaccinated"
    unique_id: "covid_nsw_state_vaccination_rate"
    icon: "mdi:needle"
    unit_of_measurement: "%"
    state: >
      {% set total_population = 8166000 %}
      {% set second_dose_total = states('sensor.covid_nsw_total_second_dose_vaccine') | int %}
      {% set state_second_dose_vaccinated_total = second_dose_total / total_population %}
      {{ (state_second_dose_vaccinated_total * 100)|round(2, 'floor') }}
    attributes:
      attribution: >
        {{ state_attr('sensor.covid_nsw_total_second_dose_vaccine', 'attribution') }}
      published: >
        {{ state_attr('sensor.covid_nsw_total_second_dose_vaccine', 'published') }}
      first_dose: >
        {% set total_population = 8166000 %}
        {% set first_dose_total = states('sensor.covid_nsw_total_first_dose_vaccine') | int %}
        {% set state_first_dose_vaccinated_total = first_dose_total / total_population %}
        {{ (state_first_dose_vaccinated_total * 100)|round(2, 'floor') }}
      first_dose_last_24_hours: >
        {% set total_population = 8166000 %}
        {% set first_dose_last24 = states('sensor.covid_nsw_last_24_hours_first_dose_vaccine') | int %}
        {% set state_first_dose_vaccinated_last24 = first_dose_last24 / total_population %}
        {{ (state_first_dose_vaccinated_last24 * 100)|round(6, 'floor') }}
      last_24_hours: >
        {% set total_population = 8166000 %}
        {% set second_dose_last24 = states('sensor.covid_nsw_last_24_hours_second_dose_vaccine') | int %}
        {% set state_second_dose_vaccinated_last24 = second_dose_last24 / total_population %}
        {{ (state_second_dose_vaccinated_last24 * 100)|round(6, 'floor') }}
  - name: "Covid NSW Last 24 Hours State"
    unique_id: "covid_nsw_last_24_hours_state"
    icon: "mdi:virus"
    unit_of_measurement: "cases"
    state: >
      {% set total = states('sensor.covid_nsw_last_24_hours_total') | int %}
      {% set overseas = states('sensor.covid_nsw_last_24_hours_overseas_source') | int %}
      {% set interstate = states('sensor.covid_nsw_last_24_hours_interstate_source') | int %}
      {% set out_of_state = (overseas + interstate) %}
      {{ (total - out_of_state) }}
    attributes:
      attribution: >
        {{ state_attr('sensor.covid_nsw_last_24_hours_total', 'attribution') }}
      published: >
        {{ state_attr('sensor.covid_nsw_last_24_hours_total', 'published') }}
