---
trigger:
  - platform: time_pattern
    hours: "/1"
sensor:
  - name: weather_outside_temperature_1hint
    unique_id: weather_outside_temperature_1hint
    state: >
      {{ states('sensor.weather_outside_temperature') | float }}
    icon: mdi:thermometer
    unit_of_measurement: "°C"
    attributes:
      timestamp: >
        {{ as_timestamp(now()) }}
