---
sensor:
  - name: opennem_graph_market
    unique_id: opennem_graph_market
    state: "{{ states('input_select.opennem_graph_entity') }}"
    attributes:
      graph_entity: >
        {%- if is_state('input_select.opennem_graph_entity', 'Australia') %}
           sensor.opennem_au
        {%- elif is_state('input_select.opennem_graph_entity', 'National Energy Market') %}
           sensor.opennem_nem
        {%- elif is_state('input_select.opennem_graph_entity', 'New South Wales') %}
           sensor.opennem_nsw
        {%- elif is_state('input_select.opennem_graph_entity', 'Queensland') %}
           sensor.opennem_qld
        {%- elif is_state('input_select.opennem_graph_entity', 'South Australia') %}
           sensor.opennem_sa
        {%- elif is_state('input_select.opennem_graph_entity', 'Tasmania') %}
           sensor.opennem_tas
        {%- elif is_state('input_select.opennem_graph_entity', 'Victoria') %}
           sensor.opennem_vic
        {%- elif is_state('input_select.opennem_graph_entity', 'Western Australia') %}
           sensor.opennem_wa
        {%- else %}
          sensor.opennem_nsw
        {%- endif %}
