---
alias: OpenUV - Update During Day (30min Interval)
id: 003780ee-c3a1-475a-b54f-8f2ef3a5c2dcß
trigger:
  platform: time_pattern
  minutes: "/30"
condition:
  condition: and
  conditions:
    - condition: sun
      after: sunrise
    - condition: sun
      before: sunset
action:
  service: openuv.update_data
