---
alias: System - HA Supervisor Addon Available
id: 5c460e93-8cb2-45ef-bbb5-a62b0035c9bc
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: binary_sensor.updater_addons
condition:
  - condition: template
    value_template: "{{ (states.binary_sensor.updater_addons.attributes.addons | count) != 'unknown' }}"
  - condition: template
    value_template: "{{ (states.binary_sensor.updater_addons.attributes.addons | count) != 0 }}"
action:
  - service: persistent_notification.create
    data_template:
      title: HA Add-ons - Updates Available
      message: >-
        {% for repo in states.binary_sensor.updater_addons.attributes.addons %}
          **{{ repo.name }}** _{{ repo["version"] }}_ -> _{{ repo["version_latest"] }}_
        {% endfor %}
  - service: notify.slack
    data_template:
      message: "HA Add-ons - Updates Available"
      target: "#tbsmarthome"
      data:
        blocks:
          - type: section
            text:
              type: mrkdwn
              text: "*HA Add-ons - Updates Available*"
          - type: section
            text:
              type: mrkdwn
              text: >-
                {% for repo in states.binary_sensor.updater_addons.attributes.addons %}
                  **{{ repo.name }}** _{{ repo["version"] }}_ -> _{{ repo["version_latest"] }}_
                {% endfor %}
