---
alias: System - New Home Assistant Version
id: 49e48ef4-c7e2-4c71-8de7-f1f04dd990f1

trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: binary_sensor.updater_core

condition:
  - condition: template
    value_template: >
      {{
      state_attr("binary_sensor.updater_core", "installed_version") != state_attr("binary_sensor.updater_core", "latest_version")
      and state_attr("binary_sensor.updater_core", "latest_version") != "unknown"
      }}

action:
  - service: notify.slack
    data_template:
      message: "New Home Assistant Version"
      target: "#tbsmarthome"
      data:
        blocks:
          - type: section
            text:
              type: mrkdwn
              text: "*New Home Assistant Version*"
          - type: section
            text:
              type: mrkdwn
              text: |
                **New Home Assistant Version**


                [{{ state_attr('binary_sensor.updater_core', 'installed_version') }} → {{ state_attr('binary_sensor.updater_core', 'latest_version') }}]({{ states('input_text.base_url') }}/hassio/dashboard) / [changelog](https://github.com/home-assistant/core/releases) / [release notes](https://www.home-assistant.io/latest-release-notes/)
  - service: persistent_notification.create
    data_template:
      title: New HA Version
      message: >-
        New Home Assistant Version
        [{{ state_attr('binary_sensor.updater_core', 'installed_version') }} → {{ state_attr('binary_sensor.updater_core', 'latest_version') }}]({{ states('input_text.base_url') }}/hassio/dashboard) / [changelog](https://github.com/home-assistant/core/releases) / [release notes](https://www.home-assistant.io/latest-release-notes/)
      notification_id: hassio_upgrade
