---
alias: HACS - Updates Available
mode: queued
max: 100
max_exceeded: silent
trigger:
  - platform: state
    entity_id: sensor.hacs
condition:
  - condition: template
    value_template: "{{ states(trigger.entity_id) != 'unknown'}}"
  - condition: template
    value_template: "{{ (states(trigger.entity_id) | float) != 0}}"
action:
  - service: persistent_notification.create
    data_template:
      title: HACS - Updates Available
      message: >-
        {% for repo in state_attr(trigger.entity_id, 'repositories') %}
          *{{ repo.display_name }}* _{{ repo["installed_version"] }}_ -> _{{ repo["available_version"] }}_
        {% endfor %}
  - service: notify.slack
    data_template:
      message: ""
      target: "#tbsmarthome"
      data:
        blocks:
          - type: section
            text:
              type: mrkdwn
              text: "*HACS - Updates Available*"
          - type: section
            text:
              type: mrkdwn
              text: >-
                {% for repo in state_attr(trigger.entity_id, 'repositories') %}
                  *{{ repo.display_name }}* _{{ repo["installed_version"] }}_ -> _{{ repo["available_version"] }}_
                {% endfor %}
