---
alias: Admin - New Home Assistant Version
trigger:
  - platform: state
    entity_id: sensor.ha_latest_version
action:
  - service: notify.slack
    data_template:
      message: "New Home Assistant Version"
      target: "#tbsmarthome"
      blocks:
        - type: section
          text:
            type: mrkdwn
            text: "*New Home Assistant Version*"
        - type: section
          text:
            type: mrkdwn
            text: |
              New Home Assistant Version
              Current - {{ states.sensor.ha_current_version.state }}
              New - {{ states.sensor.ha_latest_version.state }}
  - service: persistent_notification.create
    data_template:
      title: New HA Version
      message: >-
        New Home Assistant Version
        Current - {{ states.sensor.ha_current_version.state }}
        New - {{ states.sensor.ha_latest_version.state }}
      notification_id: hassio_upgrade
