---
alias: Admin - Home Assistant Stopped
trigger:
  - platform: homeassistant
    event: shutdown
action:
  - service: notify.slack
    data_template:
      message: "Home Assistant Stopped"
      target: "#tbsmarthome"
      data:
        blocks:
          - type: section
            text:
              type: mrkdwn
              text: "*Home Assistant Stopped*"
          - type: section
            text:
              type: mrkdwn
              text: Home Assistant Stopped
