---
alias: Admin - Home Assistant Started
trigger:
  - platform: homeassistant
    event: start
action:
  - service: notify.slack
    data_template:
      message: "Home Assistant Started"
      target: "#tbsmarthome"
      data:
        blocks:
          - type: section
            text:
              type: mrkdwn
              text: "*Home Assistant Started*"
          - type: section
            text:
              type: mrkdwn
              text: Home Assistant Started
