---
alias: Switch - Turn off Lamp
description: ""
initial_state: true
trigger:
  - device_id: 757392910449401884405f7f9e33a180
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_short_release
action:
  - entity_id: light.zha_office_light
    service: light.toggle
    data: {}
