---
id: startup_unavailable_entity_notification
alias: "Unavailable Entities Notification"
description: "Create persistent notification if there are unavailable entities, dismiss if none."
initial_state: false
mode: restart

trigger:
  - platform: state
    entity_id: sensor.unavailable_entities

action:
  - choose:
      conditions:
        - condition: numeric_state
          entity_id: sensor.unavailable_entities
          below: 1

      sequence:
        - service: persistent_notification.dismiss
          data:
            notification_id: unavailable_entities

    default:
      - service: persistent_notification.create
        data:
          title: Unavailable Entities
          message: "- {{ state_attr('sensor.unavailable_entities','entities').split(',')|join('\n- ') }}"
          notification_id: unavailable_entities
