---
resource: https://api.github.com/repos/home-assistant/core/releases?per_page=1
sensor:
  name: hass_rs_release_notes
  value_template: >
    {{ value_json[0].name }}
  json_attributes:
    - body
scan_interval: 21600
