---
homeassistant:
  customize:
    sensor.amber_general_usage_price:
      friendly_name: "Amber Electric - General Usage (E1) Price"
    sensor.amber_controlled_load_price:
      friendly_name: "Amber Electric - Controlled Load (E2) Price"
    sensor.amber_solar_feed_in_tariff:
      friendly_name: "Amber Electric - Solar Feed-In (B1) Price"

# https://github.com/lewisbenge/hass-amber-electric/issues/19
sensor:
  - platform: amberelectric
    postcode: "2340"

  - platform: template
    sensors:
      amber_peak_predicted_2h:
        friendly_name: "Amber Electric - 2hr Peak Predicted Price"
        icon_template: mdi:flash
        unit_of_measurement: "c/kWh"
        value_template: >-
          {% set forecast = states.sensor.amber_general_usage_price.attributes['price_forcecast'] %}
          {% set highest = forecast[0:4] | sort(reverse=true, attribute='price') | first() %}
          {{highest['price']}}
      amber_peak_predicted_4h:
        friendly_name: "Amber Electric - 4hr Peak Predicted Price"
        icon_template: mdi:flash
        unit_of_measurement: "c/kWh"
        value_template: >-
          {% set forecast = states.sensor.amber_general_usage_price.attributes['price_forcecast'] %}
          {% set highest = forecast[0:8] | sort(reverse=true, attribute='price') | first() %}
          {{highest['price']}}
