---
sensor:
  - platform: rest
    resource: !secret deconzapi_configurl
    name: current_version_deconz
    value_template: "{{ value_json.swversion }}"
    scan_interval: 3600

  - platform: rest
    resource: !secret deconzapi_configurl
    name: current_apiversion_deconz
    value_template: "{{ value_json.apiversion }}"
    scan_interval: 3600

  - platform: rest
    resource: https://api.github.com/repos/dresden-elektronik/deconz-rest-plugin/releases/latest
    name: latest_version_deconz
    value_template: >
      {{ value_json.tag_name.strip('_stable').lstrip('V').replace('_','.').replace('0','') }}
    scan_interval: 3600

  - platform: rest
    resource: !secret deconzapi_configurl
    name: current_firmware_conbee
    value_template: "{{ value_json.fwversion }}"
    scan_interval: 3600

  - platform: rest
    resource: !secret deconzapi_configurl
    name: zigbee_channel_deconz
    value_template: "{{ value_json.zigbeechannel }}"
    scan_interval: 3600
