---
binary_sensor:
  - platform: template
    sensors:
      networkstatus_router:
        friendly_name: UniFi UDM
        value_template: "{{ is_state('device_tracker.the_dream_police', 'home') }}"
        icon_template: >-
          mdi:router-wireless
        attribute_templates:
          ip_address: >-
            {%- set dev = 'device_tracker.the_dream_police' %}
            {{ is_state(dev, 'home') | iif( 'IP: 192.168.1.1', 'IP Address Not Available') }}
      networkstatus_switch:
        friendly_name: UniFi Switch - 8 Port 60W (Hateful8)
        value_template: "{{ is_state('device_tracker.hateful_8', 'home') }}"
        icon_template: >-
          mdi:switch
        attribute_templates:
          ip_address: >-
            "IP Address Not Available"
      networkstatus_nas_thecube2:
        friendly_name: Synology NAS (TheCube2)
        value_template: "{{ is_state('device_tracker.thecube2', 'home') }}"
        icon_template: >-
          mdi:nas
        attribute_templates:
          ip_address: >-
            {%- set dev = 'device_tracker.thecube2' %}
            {{ is_state(dev, 'home') | iif( 'IP: ' + state_attr(dev, 'ip')|default("N/A", true), 'IP Address Not Available') }}
      networkstatus_hdhomerun:
        friendly_name: HDHomeRun
        value_template: "{{ is_state('device_tracker.hdhomerun', 'home') }}"
        icon_template: >-
          mdi:television-box
        attribute_templates:
          ip_address: >-
            {%- set dev = 'device_tracker.hdhomerun' %}
            {{ is_state(dev, 'home') | iif( 'IP: ' + state_attr(dev, 'ip')|default("N/A", true), 'IP Address Not Available') }}
      networkstatus_googlenesthub:
        friendly_name: Google Home - Nest Hub
        value_template: "{{ is_state('device_tracker.google_nest_hub', 'home') }}"
        icon_template: >-
          mdi:google-home
        attribute_templates:
          ip_address: >-
            {%- set dev = 'device_tracker.google_nest_hub' %}
            {{ is_state(dev, 'home') | iif( 'IP: ' + state_attr(dev, 'ip')|default("N/A", true), 'IP Address Not Available') }}
      networkstatus_harmonyhub:
        friendly_name: Harmony Hub
        value_template: "{{ is_state('device_tracker.harmonyhub', 'home') }}"
        icon_template: >-
          mdi:remote
        attribute_templates:
          ip_address: >-
            {%- set dev = 'device_tracker.harmonyhub' %}
            {{ is_state(dev, 'home') | iif( 'IP: ' + state_attr(dev, 'ip')|default("N/A", true), 'IP Address Not Available') }}
      networkstatus_amazonalexaplus:
        friendly_name: Amazon Alexa Plus
        value_template: "{{ is_state('device_tracker.amazon_alexa_plus', 'home') }}"
        icon_template: >-
          mdi:amazon-alexa
        attribute_templates:
          ip_address: >-
            {%- set dev = 'device_tracker.amazon_alexa_plus' %}
            {{ is_state(dev, 'home') | iif( 'IP: ' + state_attr(dev, 'ip')|default("N/A", true), 'IP Address Not Available') }}
      networkstatus_sonos_office:
        friendly_name: Sonos One (Office)
        value_template: "{{ is_state('device_tracker.sonosoneoffice', 'home') }}"
        icon_template: >-
          si:sonos
        attribute_templates:
          ip_address: >-
            {%- set dev = 'device_tracker.sonosoneoffice' %}
            {{ is_state(dev, 'home') | iif( 'IP: ' + state_attr(dev, 'ip')|default("N/A", true), 'IP Address Not Available') }}
      networkstatus_appletv:
        friendly_name: Apple TV (Bedroom)
        value_template: "{{ is_state('device_tracker.appletvbedroom', 'home') }}"
        icon_template: >-
          phu:apple-tv-box
        attribute_templates:
          ip_address: >-
            {%- set dev = 'device_tracker.appletvbedroom' %}
            {{ is_state(dev, 'home') | iif( 'IP: ' + state_attr(dev, 'ip')|default("N/A", true), 'IP Address Not Available') }}
      networkstatus_xboxone:
        friendly_name: Xbox One
        value_template: "{{ is_state('device_tracker.xboxone', 'home') }}"
        icon_template: >-
          si:xbox
        attribute_templates:
          ip_address: >-
            {%- set dev = 'device_tracker.xboxone' %}
            {{ is_state(dev, 'home') | iif( 'IP: ' + state_attr(dev, 'ip')|default("N/A", true), 'IP Address Not Available') }}
      networkstatus_fetchtv:
        friendly_name: Fetch TV Mighty
        value_template: "{{ is_state('device_tracker.fetch_tv_mighty', 'home') }}"
        icon_template: >-
          mdi:television-box
        attribute_templates:
          ip_address: >-
            {%- set dev = 'device_tracker.fetch_tv_mighty' %}
            {{ is_state(dev, 'home') | iif( 'IP: ' + state_attr(dev, 'ip')|default("N/A", true), 'IP Address Not Available') }}
      networkstatus_loungetv:
        friendly_name: Sony Bravia TV - Lounge
        value_template: "{{ is_state('device_tracker.lounge_tv', 'home') }}"
        icon_template: >-
          mdi:television
        attribute_templates:
          ip_address: >-
            {%- set dev = 'device_tracker.lounge_tv' %}
            {{ is_state(dev, 'home') | iif( 'IP: ' + state_attr(dev, 'ip')|default("N/A", true), 'IP Address Not Available') }}
      networkstatus_nvidiashield:
        friendly_name: Nvidia Shield
        value_template: "{{ is_state('device_tracker.nvidia_shield', 'home') }}"
        icon_template: >-
          si:nvidia
        attribute_templates:
          ip_address: >-
            {%- set dev = 'device_tracker.nvidia_shield' %}
            {{ is_state(dev, 'home') | iif( 'IP: ' + state_attr(dev, 'ip')|default("N/A", true), 'IP Address Not Available') }}
      networkstatus_solar:
        friendly_name: Solar Inverter
        value_template: "{{ is_state('device_tracker.rakmodule_7622ae', 'home') }}"
        icon_template: >-
          mdi:solar-panel
        attribute_templates:
          ip_address: >-
            {%- set dev = 'device_tracker.rakmodule_7622ae' %}
            {{ is_state(dev, 'home') | iif( 'IP: ' + state_attr(dev, 'ip')|default("N/A", true), 'IP Address Not Available') }}
      networkstatus_bedroomtv:
        friendly_name: Samsung UA40ES6200 - Bedroom
        value_template: "{{ is_state('device_tracker.samsung_ua40es6200', 'home') }}"
        icon_template: >-
          si:samsung
        attribute_templates:
          ip_address: >-
            {%- set dev = 'device_tracker.samsung_ua40es6200' %}
            {{ is_state(dev, 'home') | iif( 'IP: ' + state_attr(dev, 'ip')|default("N/A", true), 'IP Address Not Available') }}

      networkstatus_dysonfan:
        friendly_name: Dyson Hot+Cool Link
        value_template: "{{ is_state('device_tracker.sz2_au_kka0995a', 'home') }}"
        icon_template: >-
          mdi:fan
        attribute_templates:
          ip_address: >-
            {%- set dev = 'device_tracker.sz2_au_kka0995a' %}
            {{ is_state(dev, 'home') | iif( 'IP: ' + state_attr(dev, 'ip')|default("N/A", true), 'IP Address Not Available') }}
      networkstatus_weatherflow:
        friendly_name: Weatherflow Tempest
        value_template: "{{ is_state('device_tracker.weatherflow', 'home') }}"
        icon_template: >-
          mdi:gauge
        attribute_templates:
          ip_address: >-
            {%- set dev = 'device_tracker.weatherflow' %}
            {{ is_state(dev, 'home') | iif( 'IP: ' + state_attr(dev, 'ip')|default("N/A", true), 'IP Address Not Available') }}
