---
sensor:
  - platform: template
    sensors:
      binday_next:
        unique_id: binday_next
        friendly_name: Next Bin Day
        icon_template: mdi:truck-delivery
        value_template: >-
          {%- set val = states.sensor.binday_waste.attributes['days'] | int(default=0) %}
          {%- if val == 0 %}
          {%- set day = "Today" %}
          {%- elif val == 1 %}
          {%- set day = "Tomorrow" %}
          {%- else %}
          {%- set day = "In " ~ val ~ " Days" %}
          {%- endif %}
          {%- set gwval = states.sensor.binday_greenwaste.attributes['days'] | int(default=0) %}
          {%- if gwval <= 6 %}
            {% set bins = "Red + Green" %}
          {%- else %}
            {%- set bins = "Red + Yellow" %}
          {%- endif %}
          {{ day }} - {{bins}}
      binday_date:
        unique_id: binday_date
        friendly_name: Next Collection Date
        icon_template: mdi:truck-delivery
        value_template: "{{ as_timestamp(states.sensor.binday_waste.attributes['next_date'], None)|timestamp_custom ('%a %-d %-b', 0) }}"
      binday_redbin:
        unique_id: binday_redbin
        friendly_name: General Waste
        icon_template: mdi:delete-empty
        value_template: >-
          {%- set val = states.sensor.binday_waste.attributes['days'] | int(default=0) %}
          {%- if val == 0 %}
            Today
          {%- elif val == 1 %}
            Tomorrow
          {%- elif val >= 7 %}
            Next Week
          {%- else %}
            In {{val}} Days
          {%- endif %}
      binday_greenbin:
        unique_id: binday_greenbin
        friendly_name: Green Waste
        icon_template: mdi:leaf
        value_template: >-
          {%- set val = states.sensor.binday_greenwaste.attributes['days'] | int(default=0) %}
          {%- if val == 0 %}
            Today
          {%- elif val == 1 %}
            Tomorrow
          {%- elif val >= 7 %}
            Next Week
          {%- else %}
            In {{val}} Days
          {%- endif %}
      binday_yellowbin:
        unique_id: binday_yellowbin
        friendly_name: Recycling
        icon_template: mdi:recycle
        value_template: >-
          {%- set val = states.sensor.binday_recycling.attributes['days'] | int(default=0) %}
          {%- if val == 0 %}
            Today
          {%- elif val == 1 %}
            Tomorrow
          {%- elif val >= 7 %}
            Next Week
          {%- else %}
            In {{val}} Days
          {%- endif %}
