---
homeassistant:
  customize_glob:
    "geo_location.nsw_fire_service_feed_*":
      icon: mdi:fire

geo_location:
  - platform: nsw_rural_fire_service_feed
    entity_namespace: "nswrfs"
    radius: 100
    categories:
      - "Emergency Warning"
      - "Watch and Act"
      - "Advice"
      - "Not Applicable"

sensor:
  - platform: template
    sensors:
      fires_near_me:
        friendly_name: "Fires Near Me"
        icon_template: mdi:fire
        value_template: >
          {{ states.geo_location |selectattr('attributes.source','eq','nsw_rural_fire_service_feed') | list | length  | int(default=0) }}
        unit_of_measurement: "alerts"
