---
sensor:
  - platform: template
    sensors:
      # ----- Count All Entities
      count_all_entities:
        unique_id: count_all_entities
        friendly_name: "All Entities"
        icon_template: mdi:code-tags
        value_template: >
          {{ states | count | int(default=0) }}

      count_all_domains:
        unique_id: count_all_domains
        friendly_name: "Domains in Use"
        icon_template: mdi:domain
        value_template: >
          {%- for d in states | groupby('domain') %}
          {%- if loop.first %}
          {{loop.length | int(default=0)}}
          {%- endif %}
          {%- endfor %}

      # ----- Count Automations
      count_automations:
        friendly_name: "Automations"
        icon_template: mdi:robot
        value_template: >
          {{ states.automation | list | length | int(default=0) }}

      # ----- Count Scripts
      count_scripts:
        friendly_name: "Scripts"
        icon_template: mdi:script-text-outline
        value_template: >
          {{ states.script | list | length | int(default=0) }}

      # ----- Count Device Trackers
      count_device_trackers:
        friendly_name: "Devices"
        icon_template: mdi:cellphone-link
        value_template: >
          {{ states.device_tracker | list | length | int(default=0) }}

      # ----- Count Binary Sensors
      count_binary_sensors:
        friendly_name: "Binary Sensors"
        icon_template: mdi:checkbox-multiple-marked-circle
        value_template: >
          {{ states.binary_sensor | list | length | int(default=0) }}

      # ----- Count Sensors
      count_sensors:
        friendly_name: "Sensors"
        icon_template: mdi:pulse
        value_template: >
          {{ states.sensor | list | length | int(default=0) }}

      # ----- Count Switches
      count_switches:
        friendly_name: "Switches"
        icon_template: mdi:power-socket-us
        value_template: >
          {{ states.switch | list | length | int(default=0) }}

      # ----- Count Zones
      count_zones:
        friendly_name: "Zones"
        icon_template: mdi:map-marker-radius
        value_template: >
          {{ states.zone | list | length | int(default=0) }}

      # ----- Input Booleans
      count_input_booleans:
        friendly_name: "Input Booleans"
        icon_template: mdi:toggle-switch
        value_template: >
          {{ states.input_boolean | list | length | int(default=0) }}

      # ----- Input Numbers
      count_input_numbers:
        friendly_name: "Input Numbers"
        icon_template: mdi:numeric
        value_template: >
          {{ states.input_number | list | length | int(default=0) }}

      # ----- Input Texts
      count_input_texts:
        friendly_name: "Input Texts"
        icon_template: mdi:alphabetical
        value_template: >
          {{ states.input_text | list | length | int(default=0) }}

      # ----- Input Selects
      count_input_selects:
        friendly_name: "Input Selects"
        icon_template: mdi:format-align-justify
        value_template: >
          {{ states.input_select | list | length | int(default=0) }}

      # ----- Input Date Times
      count_input_datetimes:
        friendly_name: "Input Date Times"
        icon_template: mdi:calendar
        value_template: >
          {{ states.input_datetime | list | length | int(default=0) }}

      # ----- Lights
      count_lights:
        friendly_name: "Lights"
        icon_template: mdi:lightbulb-on
        value_template: >
          {{ states.light | list | length | int(default=0) }}

      # ----- Media Players
      count_mediaplayers:
        friendly_name: "Media Players"
        icon_template: mdi:cast-connected
        value_template: >
          {{ states.media_player | list | length | int(default=0) }}

      # ----- Cameras
      count_cameras:
        friendly_name: "Cameras"
        icon_template: mdi:cctv
        value_template: >
          {{ states.camera | list | length | int(default=0) }}

      # ----- Geolocations
      count_geolocation:
        friendly_name: "Geo Locations"
        icon_template: mdi:map-plus
        value_template: >
          {{ states.geo_location | list | length | int(default=0) }}

      # ----- Groups
      count_groups:
        friendly_name: "Groups"
        icon_template: mdi:group
        value_template: >
          {{ states.group | list | length | int(default=0) }}

      # ----- Remote
      count_remotes:
        friendly_name: "Remotes"
        icon_template: mdi:remote
        value_template: >
          {{ states.remote | list | length | int(default=0) }}

      count_calendars:
        friendly_name: "Calendars"
        icon_template: mdi:calendar
        value_template: >
          {{ states.calendar | list | length | int(default=0) }}

      count_counters:
        friendly_name: "Counters"
        icon_template: mdi:counter
        value_template: >
          {{ states.counter | list | length | int(default=0) }}
