---
homeassistant:
  customize:
    binary_sensor.iss:
      icon: mdi:satellite-variant
      friendly_name: ISS Visible

binary_sensor:
  - platform: iss

sensor:
  - platform: rest
    name: ISS Pass Times
    json_attributes:
      - request
      - response
    value_template: >
      {{ value_json.message }}
    resource: !secret isspasstimes_url
    scan_interval:
      seconds: 300

  - platform: template
    sensors:
      iss_peopleinspace:
        friendly_name: "People in Space"
        value_template: '{{ states.binary_sensor.iss.attributes["number_of_people_in_space"] }}'
      iss_location:
        friendly_name: "ISS Location"
        icon_template: "mdi:satellite-variant"
        value_template: "{{ states.binary_sensor.iss.state }}"
        attribute_templates:
          latitude: '{{ states.binary_sensor.iss.attributes["lat"] }}'
          longitude: '{{ states.binary_sensor.iss.attributes["long"] }}'
