---
sensor:
  - platform: statistics
    name: lightning_counter_lasthour
    entity_id: sensor.blitzortung_lightning_counter
    sampling_size: 1000
    max_age:
      hours: 1
  - platform: statistics
    name: lightning_distance_lasthour
    entity_id: sensor.blitzortung_lightning_distance
    sampling_size: 1000
    max_age:
      hours: 1
