---
sensor:
  - platform: statistics
    name: lightning_counter_lasthour
    entity_id: sensor.blitzortung_lightning_counter
    sampling_size: 1000
    max_age:
      hours: 1
  - platform: statistics
    name: lightning_distance_lasthour
    entity_id: sensor.blitzortung_lightning_distance
    sampling_size: 1000
    max_age:
      hours: 1
  - platform: template
    sensors:
      lightning_countbolts_lasthour:
        value_template: >
          {{ states.geo_location |selectattr('attributes.source','eq','blitzortung') | list | length }}
        unit_of_measurement: "↯"
