---
homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: "fuel"
    sensor.fuelcheck_caltex_tamworth_orana_p98:
      friendly_name: Caltex Vortex98 (WhiteSt)
      icon: mdi:fuel
      <<: *customize

    sensor.fuelcheck_bp_tamworth_p98:
      friendly_name: BP Ultimate98 (Viaduct)
      icon: mdi:fuel
      <<: *customize

    sensor.fuelcheck_bp_nemingha_p98:
      friendly_name: BP Ultimate98 (Nemingha)
      icon: mdi:fuel
      <<: *customize

    sensor.fuelcheck_bp_tamworth_p98_2:
      friendly_name: BP Ultimate98 (GoonooGoonooRd)
      icon: mdi:fuel
      <<: *customize

    sensor.fuelcheck_caltex_tamworth_p98:
      friendly_name: Caltex Vortex98 (GunnedahRd)
      icon: mdi:fuel
      <<: *customize

    sensor.fuelcheck_caltex_woolworths_tamworth_p98:
      friendly_name: Caltex Vortex98 (BridgeSt)
      icon: mdi:fuel
      <<: *customize

sensor:
  - platform: nsw_fuel_station
    entity_namespace: fuelcheck
    fuel_types: P98
    station_id: 1145
    # BP Viaduct

  - platform: nsw_fuel_station
    entity_namespace: fuelcheck
    fuel_types: P98
    station_id: 16921
    # Caltex White Stret

  - platform: nsw_fuel_station
    entity_namespace: fuelcheck
    fuel_types: P98
    station_id: 573
    # Caltex Bridge St

  - platform: nsw_fuel_station
    entity_namespace: fuelcheck
    fuel_types: P98
    station_id: 2449
    # BP Nemingha

  - platform: nsw_fuel_station
    entity_namespace: fuelcheck
    fuel_types: P98
    station_id: 18350
    # Caltex Gunnedah Rd

  - platform: nsw_fuel_station
    entity_namespace: fuelcheck
    fuel_types: P98
    station_id: 1543
    # Caltex Goonoo Goonoo Road
