---
homeassistant:
  customize:
    sensor.plex_lanbandwidth:
      icon: mdi:lan
    sensor.plex_wanbandwidth:
      icon: mdi:wan
    sensor.plex_totalbandwidth:
      icon: mdi:lan-pending

sensor:
  - platform: tautulli
    api_key: !secret plex_tautulli_apikey
    host: !secret plex_tautulli_host
    port: !secret plex_tautulli_port
    monitored_conditions:
      - lan_bandwidth
      - wan_bandwidth
      - total_bandwidth
      - library_name
      - full_title
      - tagline
      - title
      - progress_percent
      - summary
      - container
      - indexes
      - libraries
      - media_type

  - platform: rest
    name: plex_tautulli_history
    json_attributes_path: "$.response.data"
    json_attributes:
      - data
    value_template: "{{ value_json['response']['result'] }}"
    resource: !secret plex_tautulli_history_url

  - platform: rest
    name: plex_tautulli_actvity
    json_attributes_path: "$.response.data"
    json_attributes:
      - data
    value_template: "{{ value_json['response']['result'] }}"
    resource: !secret plex_tautulli_activity_url

  - platform: rest
    name: plex_tautulli_toptv
    json_attributes_path: "$.response.data"
    json_attributes:
      - rows
    value_template: "{{ value_json['response']['result'] }}"
    resource: !secret plex_tautulli_toptv_url

  - platform: rest
    name: plex_tautulli_populartv
    json_attributes_path: "$.response.data"
    json_attributes:
      - rows
    value_template: "{{ value_json['response']['result'] }}"
    resource: !secret plex_tautulli_populartv_url

  - platform: rest
    name: plex_tautulli_toptv_plays
    json_attributes_path: "$.response.data"
    json_attributes:
      - rows
    value_template: "{{ value_json['response']['result'] }}"
    resource: !secret plex_tautulli_toptv_plays_url

  - platform: rest
    name: plex_tautulli_toptv_30days
    json_attributes_path: "$.response.data"
    json_attributes:
      - rows
    value_template: "{{ value_json['response']['result'] }}"
    resource: !secret plex_tautulli_toptv_30days_url

  - platform: rest
    name: plex_tautulli_topmovies
    json_attributes_path: "$.response.data"
    json_attributes:
      - rows
    value_template: "{{ value_json['response']['result'] }}"
    resource: !secret plex_tautulli_topmovies_url

  - platform: rest
    name: plex_tautulli_topusers
    json_attributes_path: "$.response.data"
    json_attributes:
      - rows
    value_template: "{{ value_json['response']['result'] }}"
    resource: !secret plex_tautulli_topusers_url

  - platform: rest
    name: plex_tautulli_watch_stats_tv
    json_attributes_path: "$.response"
    json_attributes:
      - data
    value_template: "{{ value_json['response']['result'] }}"
    resource: !secret plex_tautulli_tv_watch_stats_url

  - platform: rest
    name: plex_tautulli_watch_stats_movies
    json_attributes_path: "$.response"
    json_attributes:
      - data
    value_template: "{{ value_json['response']['result'] }}"
    resource: !secret plex_tautulli_movies_watch_stats_url

  - platform: template
    sensors:
      plex_topmovie:
        friendly_name: Plex Top Movie
        icon_template: mdi:plex
        value_template: >
          {{ state_attr('sensor.tautulli', 'Top Movie')|default("No Top Movie", true) }}
      plex_toptvshow:
        friendly_name: Plex Top TV Show
        icon_template: mdi:plex
        value_template: >
          {{ state_attr('sensor.tautulli', 'Top TV Show')|default("No Top TV Show", true) }}
      plex_topuser:
        friendly_name: Plex Top User
        icon_template: mdi:plex
        value_template: >
          {{ state_attr('sensor.tautulli', 'Top User')|default("No Top User", true)}}
      plex_lanbandwidth:
        value_template: >
          {{ (state_attr('sensor.tautulli','lan_bandwidth') / 1024) | round(2) | float(default=0) }}
        unit_of_measurement: "Mbps"
        friendly_name: "Plex LAN Bandwidth"
        icon_template: mdi:plex
      plex_wanbandwidth:
        value_template: >
          {{ (state_attr('sensor.tautulli','wan_bandwidth') / 1024) | round(2) | float(default=0) }}
        unit_of_measurement: "Mbps"
        friendly_name: "Plex WAN Bandwidth"
        icon_template: mdi:plex
      plex_totalbandwidth:
        value_template: >
          {{ (state_attr('sensor.tautulli','total_bandwidth') / 1024) | round(2) | float(default=0) }}
        unit_of_measurement: "Mbps"
        friendly_name: "Plex Total Bandwidth"
        icon_template: mdi:plex
