---
sensor:

  - platform: rest
    name: plex_tautulli_history
    json_attributes_path: "$.response.data"
    json_attributes:
      - data
    value_template: "{{ value_json['response']['result'] }}"
    resource: !secret plex_tautulli_history_url

  - platform: rest
    name: plex_tautulli_actvity
    json_attributes_path: "$.response.data"
    json_attributes:
      - data
    value_template: "{{ value_json['response']['result'] }}"
    resource: !secret plex_tautulli_activity_url

  - platform: rest
    name: plex_tautulli_toptv
    json_attributes_path: "$.response.data"
    json_attributes:
      - rows
    value_template: "{{ value_json['response']['result'] }}"
    resource: !secret plex_tautulli_toptv_url

  - platform: rest
    name: plex_tautulli_populartv
    json_attributes_path: "$.response.data"
    json_attributes:
      - rows
    value_template: "{{ value_json['response']['result'] }}"
    resource: !secret plex_tautulli_populartv_url

  - platform: rest
    name: plex_tautulli_toptv_plays
    json_attributes_path: "$.response.data"
    json_attributes:
      - rows
    value_template: "{{ value_json['response']['result'] }}"
    resource: !secret plex_tautulli_toptv_plays_url

  - platform: rest
    name: plex_tautulli_toptv_30days
    json_attributes_path: "$.response.data"
    json_attributes:
      - rows
    value_template: "{{ value_json['response']['result'] }}"
    resource: !secret plex_tautulli_toptv_30days_url

  - platform: rest
    name: plex_tautulli_topmovies
    json_attributes_path: "$.response.data"
    json_attributes:
      - rows
    value_template: "{{ value_json['response']['result'] }}"
    resource: !secret plex_tautulli_topmovies_url

  - platform: rest
    name: plex_tautulli_topusers
    json_attributes_path: "$.response.data"
    json_attributes:
      - rows
    value_template: "{{ value_json['response']['result'] }}"
    resource: !secret plex_tautulli_topusers_url

  - platform: rest
    name: plex_tautulli_watch_stats_tv
    json_attributes_path: "$.response"
    json_attributes:
      - data
    value_template: "{{ value_json['response']['result'] }}"
    resource: !secret plex_tautulli_tv_watch_stats_url

  - platform: rest
    name: plex_tautulli_watch_stats_movies
    json_attributes_path: "$.response"
    json_attributes:
      - data
    value_template: "{{ value_json['response']['result'] }}"
    resource: !secret plex_tautulli_movies_watch_stats_url
