---
homeassistant:
  customize:
    sensor.tbsh1_package_updates:
      icon: mdi:upload-network-outline
    sensor.tbsh03_package_updates:
      icon: mdi:upload-network-outline
    sensor.tbsh01_security_updates:
      icon: mdi:security-network
    sensor.tbsh03_security_updates:
      icon: mdi:security-network

sensor:
  - platform: command_line
    name: TBSH1 Package Updates
    scan_interval: 300
    command: ssh -i /config/.ssh/id_rsa -o 'StrictHostKeyChecking=no' tbsmarthome@192.168.1.91 -T /usr/lib/update-notifier/apt-check 2>&1 | cut -d ';' -f 1

  - platform: command_line
    name: vmTBSH01 Security Updates
    scan_interval: 300
    command: ssh -i /config/.ssh/id_rsa -o 'StrictHostKeyChecking=no' tbsmarthome@192.168.1.91 -T /usr/lib/update-notifier/apt-check 2>&1 | cut -d ';' -f 2

  - platform: command_line
    name: TBSH03 Package Updates
    scan_interval: 300
    command: ssh -i /config/.ssh/id_rsa -o 'StrictHostKeyChecking=no' tbsmarthome@192.168.1.65 -T /usr/lib/update-notifier/apt-check 2>&1 | cut -d ';' -f 1

  - platform: command_line
    name: TBSH03 Security Updates
    scan_interval: 300
    command: ssh -i /config/.ssh/id_rsa -o 'StrictHostKeyChecking=no' tbsmarthome@192.168.1.65 -T /usr/lib/update-notifier/apt-check 2>&1 | cut -d ';' -f 2
