---
sensor:
  - platform: mqtt
    name: solar_output_power
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/output_power"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: solar_daily_yield
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/daily_yield"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: solar_total_yield
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/total_yield"
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: solar_total_running_time
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/total_running_time"
    unit_of_measurement: "h"
  - platform: mqtt
    name: solar_internal_temperature
    icon: mdi:thermometer
    state_topic: "modbus4mqtt/internal_temperature"
    unit_of_measurement: "°C"
  - platform: mqtt
    name: solar_dc_output
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/dc_output"
    unit_of_measurement: "W"
  - platform: mqtt
    name: solar_phase_a_voltage
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/phase_a_voltage"
    unit_of_measurement: "V"
  - platform: mqtt
    name: solar_phase_a_current
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/phase_a_current"
    unit_of_measurement: "A"
  - platform: mqtt
    name: solar_ac_output
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/ac_output"
    unit_of_measurement: "W"
  - platform: mqtt
    name: solar_power_factor
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/power_factor"
    unit_of_measurement: ""
  - platform: mqtt
    name: solar_grid_frequency
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/grid_frequency"
    unit_of_measurement: "Hz"
  - platform: mqtt
    name: solar_device_state
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/device_state"
    unit_of_measurement: ""
  - platform: mqtt
    name: solar_daily_running_time
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/daily_running_time"
    unit_of_measurement: "m"
  - platform: mqtt
    name: solar_solar_to_house
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/solar_to_house"
    unit_of_measurement: "kW"
  - platform: mqtt
    name: solar_solar_to_grid_raw
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/solar_to_grid"
    unit_of_measurement: "kW"
  - platform: mqtt
    name: solar_solar_generation
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/solar_generation"
    unit_of_measurement: "kW"
  - platform: mqtt
    name: solar_feedin_total
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/feedin_total"
    unit_of_measurement: "kW"
  - platform: mqtt
    name: solar_grid_total
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/grid_total"
    unit_of_measurement: "kW"
  - platform: mqtt
    name: solar_grid_daily
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/grid_daily"
    unit_of_measurement: "kW"
  - platform: mqtt
    name: solar_pv1_voltage
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/pv1_voltage"
    unit_of_measurement: "V"
  - platform: mqtt
    name: solar_pv1_current
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/pv1_current"
    unit_of_measurement: "A"
  - platform: mqtt
    name: solar_pv2_voltage
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/pv2_voltage"
    unit_of_measurement: "V"
  - platform: mqtt
    name: solar_pv2_current
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/pv2_current"
    unit_of_measurement: "A"
  - platform: mqtt
    name: solar_grid_voltage
    icon: mdi:solar-power
    state_topic: "modbus4mqtt/grid_voltage"
    unit_of_measurement: "V"
  - platform: template
    sensors:
      solar_daily_yield_clean:
        friendly_name: Daily Yield
        unit_of_measurement: "kWh"
        icon_template: mdi:solar-power
        value_template: "{{ ( states.sensor.solar_daily_yield.state | float ) / (10) }}"
      solar_total_yield_clean:
        friendly_name: Total Yield
        unit_of_measurement: "MWh"
        icon_template: mdi:solar-power
        value_template: "{{ ( states.sensor.solar_total_yield.state | float ) / (1000) }}"

      solar_dc_output_clean:
        friendly_name: DC Output
        unit_of_measurement: "kW"
        icon_template: mdi:solar-power
        value_template: "{{ ( states.sensor.solar_dc_output.state | float ) / (1000) }}"
      solar_to_grid_clean:
        friendly_name: Solar to Grid
        unit_of_measurement: "kW"
        icon_template: mdi:solar-power
        value_template: >
          {% set gen = states.sensor.solar_solar_generation.state | float %}
          {% set hse = states.sensor.solar_solar_to_house.state | float %}
          {% if hse >= gen %}
            0.00
          {% else %}
            {{ (gen - hse) | round(2) }}
          {% endif %}
      solar_grid_usage:
        friendly_name: Grid Usage
        unit_of_measurement: "kW"
        icon_template: mdi:solar-power
        value_template: >
          {% set gen = states.sensor.solar_solar_generation.state | float %}
          {% set hse = states.sensor.solar_solar_to_house.state | float %}
          {{ (gen - hse) | round(2) }}
      solar_house_from_grid_clean:
        friendly_name: Solar Power from Grid
        unit_of_measurement: "kW"
        icon_template: mdi:solar-power
        value_template: >
          {% set gen = states.sensor.solar_solar_generation.state | float %}
          {% set hse = states.sensor.solar_solar_to_house.state | float %}
          {% if hse >= gen %}
            {{ (hse - gen) | round(2) }}
          {% else %}
            0.00
          {% endif %}
      solar_daily_running_time_clean:
        friendly_name: Daily Running Time
        icon_template: mdi:solar-power
        value_template: >
          {% set time = states.sensor.solar_daily_running_time.state | float %}
          {% set time = time * 60 %}
          {% set minutes = ((time % 3600) / 60) | int %}
          {% set hours = ((time % 86400) / 3600) | int %}
          {% set days = (time / 86400) | int %}

          {%- if time < 60 -%}
            Less than a minute
          {%- else -%}
            {%- if days > 0 -%}
              {%- if days == 1 -%}
                1 day
              {%- else -%}
                {{ days }} days
              {%- endif -%}
            {%- endif -%}
            {%- if hours > 0 -%}
              {%- if days > 0 -%}
                {{ ', ' }}
              {%- endif -%}
              {%- if hours == 1 -%}
                1 hour
              {%- else -%}
                {{ hours }} hours
              {%- endif -%}
            {%- endif -%}
            {%- if minutes > 0 -%}
              {%- if days > 0 or hours > 0 -%}
                {{ ', ' }}
              {%- endif -%}
              {%- if minutes == 1 -%}
                1 minute
              {%- else -%}
                {{ minutes }} minutes
              {%- endif -%}
            {%- endif -%}
          {%- endif -%}

      solar_total_running_time_clean:
        friendly_name: Total Running Time
        icon_template: mdi:solar-power
        value_template: >
          {% set time = states.sensor.solar_total_running_time.state | float %}
          {% set time = time * 60 %}
          {% set minutes = ((time % 3600) / 60) | int %}
          {% set hours = ((time % 86400) / 3600) | int %}
          {% set days = (time / 86400) | int %}

          {%- if time < 60 -%}
            Less than a minute
          {%- else -%}
            {%- if days > 0 -%}
              {%- if days == 1 -%}
                1 day
              {%- else -%}
                {{ days }} days
              {%- endif -%}
            {%- endif -%}
            {%- if hours > 0 -%}
              {%- if days > 0 -%}
                {{ ', ' }}
              {%- endif -%}
              {%- if hours == 1 -%}
                1 hour
              {%- else -%}
                {{ hours }} hours
              {%- endif -%}
            {%- endif -%}
            {%- if minutes > 0 -%}
              {%- if days > 0 or hours > 0 -%}
                {{ ', ' }}
              {%- endif -%}
              {%- if minutes == 1 -%}
                1 minute
              {%- else -%}
                {{ minutes }} minutes
              {%- endif -%}
            {%- endif -%}
          {%- endif -%}

  - platform: filter
    name: solar_solar_to_house_filtered
    entity_id: sensor.solar_solar_to_house
    filters:
      - filter: time_throttle
        window_size: "00:05"

  - platform: filter
    name: solar_house_from_grid_clean_filtered
    entity_id: sensor.solar_house_from_grid_clean
    filters:
      - filter: time_throttle
        window_size: "00:05"

  - platform: filter
    name: solar_solar_generation_filtered
    entity_id: sensor.solar_solar_generation
    filters:
      - filter: time_throttle
        window_size: "00:05"

  - platform: filter
    name: solar_solar_generation_filtered_avg
    entity_id: sensor.solar_solar_generation
    filters:
      - filter: time_simple_moving_average
        window_size: "00:01"
        precision: 2

  - platform: filter
    name: solar_daily_yield_clean_filtered
    entity_id: sensor.solar_daily_yield_clean
    filters:
      - filter: time_throttle
        window_size: "00:05"

utility_meter:
  meter_solar_house_daily:
    source: sensor.solar_solar_to_house_filtered
    cycle: daily
  meter_solar_grid_daily:
    source: sensor.solar_to_grid_clean_filtered
    cycle: daily
