---
sensor:
  - platform: mqtt
    icon: mdi:solar-power
    name: sungrowsolar_alldata
    state_topic: solar/inverter_SG5KD/SENSOR
    value_template: "{{value_json.daily_power_yields}}"
    unit_of_measurement: "kW"
    json_attributes_topic: solar/inverter_SG5KD/SENSOR
  - platform: integration
    source: sensor.sungrowsolar_solar_production
    name: SungrowSolar Solar Production (kWh)
  - platform: integration
    source: sensor.sungrowsolar_return_to_grid
    name: SungrowSolar Returned to Grid (kWh)
  - platform: integration
    source: sensor.sungrowsolar_import_from_grid
    name: SungrowSolar Grid Consumption (kWh)

template:
  - sensor:
      - name: "sungrowsolar_solar_production"
        unique_id: sungrowsolar_solar_production
        unit_of_measurement: "kW"
        device_class: power
        state: >
          {{ ( states.sensor.inverter_active_power.state | float ) / (1000) }}
      - name: "sungrowsolar_return_to_grid"
        unique_id: sungrowsolar_return_to_grid
        unit_of_measurement: "kW"
        device_class: power
        state: >
          {{ ( states.sensor.inverter_export_to_grid.state | float ) / (1000) }}
      - name: "sungrowsolar_import_from_grid"
        unique_id: sungrowsolar_import_from_grid
        unit_of_measurement: "kW"
        device_class: power
        state: >
          {{ ( states.sensor.inverter_import_from_grid.state | float ) / (1000) }}
      - name: "sungrowsolar_load_power"
        unique_id: sungrowsolar_load_power
        unit_of_measurement: "kW"
        device_class: power
        state: >
          {{ ( state_attr('sensor.sungrowsolar_alldata', 'load_power') | float ) / (1000) }}
      - name: "sungrowsolar_export_to_grid"
        unique_id: sungrowsolar_export_to_grid
        unit_of_measurement: "kW"
        device_class: power
        state: >
          {{ -( state_attr('sensor.sungrowsolar_alldata', 'export_to_grid') | float ) / (1000) }}
      - name: "sungrowsolar_daily_power_yields"
        unique_id: sungrowsolar_daily_power_yields
        unit_of_measurement: "kWh"
        device_class: energy
        state: >
          {{ ( state_attr('sensor.sungrowsolar_alldata', 'daily_power_yields') | float ) }}
      - name: "sungrowsolar_daily_export_energy"
        unique_id: sungrowsolar_daily_export_energy
        unit_of_measurement: "kWh"
        device_class: energy
        state: >
          {{ ( state_attr('sensor.sungrowsolar_alldata', 'daily_export_energy') | float ) }}
      - name: "sungrowsolar_daily_import_energy"
        unique_id: sungrowsolar_daily_import_energy
        unit_of_measurement: "kWh"
        device_class: energy
        state: >
          {{ ( state_attr('sensor.sungrowsolar_alldata', 'daily_import_energy') | float ) }}
      - name: "sungrowsolar_daily_direct_energy_consumption"
        unique_id: sungrowsolar_daily_direct_energy_consumption
        unit_of_measurement: "kWh"
        device_class: energy
        state: >
          {{ ( state_attr('sensor.sungrowsolar_alldata', 'daily_direct_energy_consumption') | float ) }}
