rest:
  - resource: http://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard
    scan_interval: 86400
    sensor:
      - name: Patriots Score
        value_template: >
          {% for event in value_json["events"] %}
            {% if 'NE' in event.shortName %}
              {% for competition in event["competitions"] %}
                {% if competition.status.type.state != 'pre' and  competition.status.type.state != 'post' %}
                  {% for competitor in competition["competitors"] %}
                    {% if  competitor.team.abbreviation == 'NE' %}
                      {{ competitor.score }}
                    {% endif %}
                  {% endfor %}
                {% else %}
                  0
                {% endif %}
              {% endfor %}
            {% endif %}
          {% endfor %}

      - name: Patriots Display Name
        value_template: >
          {% for event in value_json["events"] %}
            {% if 'NE' in event.shortName %}
              {% for competition in event["competitions"] %}
                {% for competitor in competition["competitors"] %}
                  {% if  competitor.team.abbreviation == 'NE' %}
                    {{ competitor.team.shortDisplayName }}
                  {% endif %}
                {% endfor %}
              {% endfor %}
            {% endif %}
          {% endfor %}

      - name: Patriots Display Logo
        value_template: >
          {% for event in value_json["events"] %}
            {% if 'NE' in event.shortName %}
              {% for competition in event["competitions"] %}
                {% for competitor in competition["competitors"] %}
                  {% if  competitor.team.abbreviation == 'NE' %}
                    {{ competitor.team.logo }}
                  {% endif %}
                {% endfor %}
              {% endfor %}
            {% endif %}
          {% endfor %}

      - name: Patriots Opponent Score
        value_template: >
          {% for event in value_json["events"] %}
            {% if 'NE' in event.shortName %}
              {% for competition in event["competitions"] %}
                {% if competition.status.type.state != 'pre' and  competition.status.type.state != 'post' %}
                  {% for competitor in competition["competitors"] %}
                    {% if  competitor.team.abbreviation != 'NE' %}
                      {{ competitor.score }}
                    {% endif %}
                  {% endfor %}
                {% else %}
                  0
                {% endif %}
              {% endfor %}
            {% endif %}
          {% endfor %}

      - name: Patriots Opponent Name
        value_template: >
          {% for event in value_json["events"] %}
            {% if 'NE' in event.shortName %}
              {% for competition in event["competitions"] %}
                {% for competitor in competition["competitors"] %}
                  {% if  competitor.team.abbreviation != 'NE' %}
                    {{ competitor.team.shortDisplayName }}
                  {% endif %}
                {% endfor %}
              {% endfor %}
            {% endif %}
          {% endfor %}

      - name: Patriots Opponent Logo
        value_template: >
          {% for event in value_json["events"] %}
            {% if 'NE' in event.shortName %}
              {% for competition in event["competitions"] %}
                {% for competitor in competition["competitors"] %}
                  {% if  competitor.team.abbreviation != 'NE' %}
                    {{ competitor.team.logo }}
                  {% endif %}
                {% endfor %}
              {% endfor %}
            {% endif %}
          {% endfor %}

      - name: Patriots Game Status
        value_template: >
          {% for event in value_json["events"] %}
            {% if 'NE' in event.shortName %}
              {% for competition in event["competitions"] %}
                {% if competition.status.type.state == 'pre' %}
                    Pregame
                {% elif competition.status.type.state == 'post' %}
                    Final
                {% else %}
                    Q{{ competition.status.period }}
                {% endif %}
              {% endfor %}
            {% endif %}
          {% endfor %}

      - name: Patriots Game Clock
        value_template: >
          {% for event in value_json["events"] %}
            {% if 'NE' in event.shortName %}
              {% for competition in event["competitions"] %}
                  {{ competition.status.displayClock }}
              {% endfor %}
            {% endif %}
          {% endfor %}

      - name: Patriots Game Time
        value_template: >
          {% for event in value_json["events"] %}
            {% if 'NE' in event.shortName %}
              {% for competition in event["competitions"] %}
                {{ competition.date }}
              {% endfor %}
            {% endif %}
          {% endfor %}

      - name: Patriots Game City
        value_template: >
          {% for event in value_json["events"] %}
            {% if 'NE' in event.shortName %}
              {% for competition in event["competitions"] %}
                {{ competition.venue.address.city }}, {{ competition.venue.address.state }}
              {% endfor %}
            {% endif %}
          {% endfor %}

      - name: Patriots Game Venue
        value_template: >
          {% for event in value_json["events"] %}
            {% if 'NE' in event.shortName %}
              {% for competition in event["competitions"] %}
                {{ competition.venue.fullName }}
              {% endfor %}
            {% endif %}
          {% endfor %}

      - name: Patriots Game Broadcast
        value_template: >
          {% for event in value_json["events"] %}
            {% if 'NE' in event.shortName %}
              {% for competition in event["competitions"] %}
                {% for broadcast in competition["broadcasts"] %}
                    {% for name in broadcast["names"] %}
                        {{ name }}
                    {% endfor %}
                {% endfor %}
              {% endfor %}
            {% endif %}
          {% endfor %}

sensor:
  - platform: template
    sensors:
      patriots_sb_score:
        value_template: >
          {{ states('sensor.patriots_score') }} 
        friendly_name_template: >
          {{ states('sensor.patriots_display_name') }}
        entity_picture_template: >-
          {{ states('sensor.patriots_display_logo') }}
      patriots_sb_opponent_score:
        value_template: >
          {{ states('sensor.patriots_opponent_score') }} 
        friendly_name_template: >
          {{ states('sensor.patriots_opponent_name') }}
        entity_picture_template: >-
          {{ states('sensor.patriots_opponent_logo') }}
      sb_state_clock:
        value_template: >
          {{ states('sensor.patriots_game_clock') }}
        friendly_name_template: >
          {{ states('sensor.patriots_game_status') }}
      sb_venue_date:
        value_template: >
          {{ as_timestamp(strptime(as_datetime(states.sensor.patriots_game_time.state), '%Y-%m-%d %H:%M:%S%z')) | timestamp_custom("%A @ %-I:%M %p") }}
        friendly_name_template: >
          {{ states('sensor.patriots_game_venue') }}
      sb_city_broadcast: 
        value_template: >
          {{ states('sensor.patriots_game_broadcast') }}
        friendly_name_template: >
          {{ states('sensor.patriots_game_city') }}