---
sensor:
  - platform: nhl_api
    team_id: 24
    name: "NHL Anaheim Ducks"
  - platform: template
    sensors:
      nhl_anaheim_ducks_away_team:
        friendly_name_template: "{{ states.sensor.nhl_anaheim_ducks.attributes.away_name }}"
        value_template: "{{ states.sensor.nhl_anaheim_ducks.attributes.away_score }}"
        entity_picture_template: "{{ states.sensor.nhl_anaheim_ducks.attributes.away_logo }}"
      nhl_anaheim_ducks_home_team:
        friendly_name_template: "{{ states.sensor.nhl_anaheim_ducks.attributes.home_name }}"
        value_template: "{{ states.sensor.nhl_anaheim_ducks.attributes.home_score }}"
        entity_picture_template: "{{ states.sensor.nhl_anaheim_ducks.attributes.home_logo }}"
