---
sensor:
  - platform: command_line
    name: Supervisor Installed
    command: 'curl http://supervisor/supervisor/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version,"update_available":.data.update_available,"addons":[.data.addons[] | select(.update_available)]}'''
    value_template: "{{ value_json.addons | length }}"
    unit_of_measurement: pending update(s)
    json_attributes:
      - update_available
      - newest_version
      - current_version
      - addons

  - platform: command_line
    name: DNS Installed
    command: 'curl http://supervisor/dns/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version, "update_available":.data.update_available}'''
    value_template: "{% if value_json.update_available %}on{% else %}off{% endif %}"
    json_attributes:
      - update_available
      - newest_version
      - current_version

  - platform: command_line
    name: Audio Installed
    command: 'curl http://supervisor/audio/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version, "update_available":.data.update_available}'''
    value_template: "{% if value_json.update_available %}on{% else %}off{% endif %}"
    json_attributes:
      - update_available
      - newest_version
      - current_version

  - platform: command_line
    name: ClI Installed
    command: 'curl http://supervisor/cli/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version, "update_available":.data.update_available}'''
    value_template: "{% if value_json.update_available %}on{% else %}off{% endif %}"
    json_attributes:
      - update_available
      - newest_version
      - current_version

  - platform: command_line
    name: Multicast Installed
    command: 'curl http://supervisor/multicast/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version, "update_available":.data.update_available}'''
    value_template: "{% if value_json.update_available %}on{% else %}off{% endif %}"
    json_attributes:
      - update_available
      - newest_version
      - current_version

  - platform: command_line
    name: Observer Installed
    command: 'curl http://supervisor/observer/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version, "update_available":.data.update_available}'''
    value_template: "{% if value_json.update_available %}on{% else %}off{% endif %}"
    json_attributes:
      - update_available
      - newest_version
      - current_version

  - platform: command_line
    name: Core Installed
    command: 'curl http://supervisor/core/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version, "update_available":.data.update_available}'''
    value_template: "{% if value_json.update_available %}on{% else %}off{% endif %}"
    json_attributes:
      - update_available
      - newest_version
      - current_version

  - platform: template
    sensors:
      current_supervisor_installed:
        value_template: '{{ states.sensor.supervisor_installed.attributes["current_version"] }}'
      current_dns_installed:
        value_template: '{{ states.sensor.dns_installed.attributes["current_version"] }}'
      current_audio_installed:
        value_template: '{{ states.sensor.audio_installed.attributes["current_version"] }}'
      current_cli_installed:
        value_template: '{{ states.sensor.cli_installed.attributes["current_version"] }}'
      current_multicast_installed:
        value_template: '{{ states.sensor.multicast_installed.attributes["current_version"] }}'
      current_multicast_latest:
        value_template: '{{ states.sensor.multicast_installed.attributes["newest_version"] }}'
      current_observer_installed:
        value_template: '{{ states.sensor.observer_installed.attributes["current_version"] }}'
      current_observer_latest:
        value_template: '{{ states.sensor.observer_installed.attributes["newest_version"] }}'
      current_core_installed:
        value_template: '{{ states.sensor.core_installed.attributes["current_version"] }}'
      current_core_latest:
        value_template: '{{ states.sensor.core_installed.attributes["newest_version"] }}'

  - platform: rest
    resource: https://version.home-assistant.io/beta.json
    name: Home Assistant Beta Supervised Versions
    scan_interval: 7200
    json_attributes:
      - supervisor
      - homeassistant
      - hassos
      - hassos-cli
      - cli
      - dns
      - audio
    value_template: "OK"
  - platform: template
    sensors:
      current_supervisor_beta:
        value_template: '{{ states.sensor.home_assistant_beta_supervised_versions.attributes["supervisor"] }}'
      current_ha_beta:
        value_template: '{{ states.sensor.home_assistant_beta_supervised_versions.attributes["homeassistant"]["intel-nuc"] }}'
      current_hassos_beta:
        value_template: '{{ states.sensor.home_assistant_beta_supervised_versions.attributes["hassos"]["intel-nuc"] }}'
      current_hassos_cli_beta:
        value_template: '{{ states.sensor.home_assistant_beta_supervised_versions.attributes["hassos-cli"] }}'
      current_cli_beta:
        value_template: '{{ states.sensor.home_assistant_beta_supervised_versions.attributes["cli"] }}'
      current_dns_beta:
        value_template: '{{ states.sensor.home_assistant_beta_supervised_versions.attributes["dns"] }}'
      current_audio_beta:
        value_template: '{{ states.sensor.home_assistant_beta_supervised_versions.attributes["audio"] }}'
  - platform: rest
    resource: https://version.home-assistant.io/stable.json
    name: Home Assistant Supervised Stable Versions
    scan_interval: 7200
    json_attributes:
      - supervisor
      - homeassistant
      - hassos
      - hassos-cli
      - cli
      - dns
      - audio
    value_template: "OK"
  - platform: template
    sensors:
      current_supervisor_stable:
        value_template: '{{ states.sensor.home_assistant_supervised_stable_versions.attributes["supervisor"] }}'
      current_ha_stable:
        value_template: '{{ states.sensor.home_assistant_supervised_stable_versions.attributes["homeassistant"]["intel-nuc"] }}'
      current_hassos_stable:
        value_template: '{{ states.sensor.home_assistant_supervised_stable_versions.attributes["hassos"]["intel-nuc"] }}'
      current_hassos_cli_stable:
        value_template: '{{ states.sensor.home_assistant_supervised_stable_versions.attributes["hassos-cli"] }}'
      current_cli_stable:
        value_template: '{{ states.sensor.home_assistant_supervised_stable_versions.attributes["cli"] }}'
      current_dns_stable:
        value_template: '{{ states.sensor.home_assistant_supervised_stable_versions.attributes["dns"] }}'
      current_audio_stable:
        value_template: '{{ states.sensor.home_assistant_supervised_stable_versions.attributes["audio"] }}'
  - platform: rest
    resource: https://version.home-assistant.io/dev.json
    name: Home Assistant Supervised Dev Versions
    scan_interval: 7200
    json_attributes:
      - supervisor
      - homeassistant
      - hassos
      - hassos-cli
      - cli
      - dns
      - audio
    value_template: "OK"
  - platform: template
    sensors:
      current_supervisor_dev:
        value_template: '{{ states.sensor.home_assistant_supervised_dev_versions.attributes["supervisor"] }}'
      current_ha_dev:
        value_template: '{{ states.sensor.home_assistant_supervised_dev_versions.attributes["homeassistant"]["intel-nuc"] }}'
      current_hassos_dev:
        value_template: '{{ states.sensor.home_assistant_supervised_dev_versions.attributes["hassos"]["intel-nuc"] }}'
      current_hassos_cli_dev:
        value_template: '{{ states.sensor.home_assistant_supervised_dev_versions.attributes["hassos-cli"] }}'
      current_cli_dev:
        value_template: '{{ states.sensor.home_assistant_supervised_dev_versions.attributes["cli"] }}'
      current_dns_dev:
        value_template: '{{ states.sensor.home_assistant_supervised_dev_versions.attributes["dns"] }}'
      current_audio_dev:
        value_template: '{{ states.sensor.home_assistant_supervised_dev_versions.attributes["audio"] }}'

binary_sensor:
  # True if there's updates available for any HACS components, Addons or the Host
  - platform: threshold
    name: Updater HACS
    entity_id: sensor.hacs_updates
    upper: 0.5
  - platform: threshold
    name: Updater Addons
    entity_id: sensor.supervisor_installed
    upper: 0.5
  - platform: threshold
    name: Updater Host
    entity_id: sensor.host_installed
    upper: 0.5

  - platform: template
    sensors:
      # True if there's an update available for supervisor
      updater_supervisor:
        friendly_name: "Updater Supervisor"
        device_class: problem
        value_template: "{{ state_attr('sensor.supervisor_installed', 'update_available') }}"
        availability_template: "{{ states('sensor.supervisor_installed') | int(-1) > -1 }}"
