---
homeassistant:
  customize:
    input_text.base_url:
      hidden: true
    binary_sensor.updater:
      friendly_name: Core
    sensor.core_updates:
      friendly_name: Core Update Available
    sensor.supervisor_updates:
      friendly_name: Supervisor Update Available
    sensor.os_updates:
      friendly_name: OS Update Available
    sensor.addons_updates:
      friendly_name: Supervisor Add-ons Update Available
    sensor.hacs:
      friendly_name: HACS Integrations/Frontend Update Available

binary_sensor:
  - platform: template
    sensors:
      updater_available:
        friendly_name: Update Status
        unique_id: updater_available
        icon_template: "{{ 'mdi:cloud-upload' if is_state('binary_sensor.system_update','on') else 'mdi:cloud-check' }}"
        device_class: problem
        value_template: >
          {{ is_state('binary_sensor.updater','on')
              or is_state('binary_sensor.updater_core','on')
              or is_state('binary_sensor.updater_supervisor','on')
              or is_state('binary_sensor.updater_os','on')
              or is_state('binary_sensor.updater_addons','on')
              or is_state('binary_sensor.updater_hacs','on')
              or is_state('binary_sensor.updater_cli','on')
              or is_state('binary_sensor.updater_dns','on')
              or is_state('binary_sensor.updater_audio','on')
              or is_state('binary_sensor.updater_multicast','on') }}
      updater_core:
        friendly_name: Core
        device_class: problem
        value_template: "{{ states('sensor.core_updates') }}"
        attribute_templates:
          installed_version: "{{ state_attr('sensor.core_updates', 'installed_version') }}"
          latest_version: "{{ state_attr('sensor.core_updates', 'latest_version') }}"

      updater_supervisor:
        friendly_name: Supervisor
        device_class: problem
        value_template: "{{ states('sensor.supervisor_updates') }}"
        attribute_templates:
          installed_version: "{{ state_attr('sensor.supervisor_updates', 'installed_version') }}"
          latest_version: "{{ state_attr('sensor.supervisor_updates', 'latest_version') }}"

      updater_os:
        friendly_name: Operating System
        device_class: problem
        value_template: "{{ states('sensor.os_updates') }}"
        attribute_templates:
          installed_version: "{{ state_attr('sensor.os_updates', 'installed_version') }}"
          latest_version: "{{ state_attr('sensor.os_updates', 'latest_version') }}"

      updater_addons:
        friendly_name: Supervisor Add-ons
        device_class: problem
        value_template: "{{ states('sensor.addons_updates')|int != 0 }}"
        attribute_templates:
          addons: "{{ state_attr('sensor.addons_updates', 'addons') }}"

      updater_hacs:
        friendly_name: HACS Integrations/Frontend
        device_class: problem
        value_template: "{{ states('sensor.hacs')|int != 0 }}"
        attribute_templates:
          repositories: "{{ state_attr('sensor.hacs', 'repositories') }}"
      updater_audio:
        friendly_name: Audio
        device_class: problem
        value_template: "{{ states('sensor.audio_updates') }}"
        attribute_templates:
          installed_version: "{{ state_attr('sensor.audio_updates', 'installed_version') }}"
          latest_version: "{{ state_attr('sensor.audio_updates', 'latest_version') }}"
      updater_dns:
        friendly_name: DNS
        device_class: problem
        value_template: "{{ states('sensor.dns_updates') }}"
        attribute_templates:
          installed_version: "{{ state_attr('sensor.dns_updates', 'installed_version') }}"
          latest_version: "{{ state_attr('sensor.dns_updates', 'latest_version') }}"
      updater_cli:
        friendly_name: CLI
        device_class: problem
        value_template: "{{ states('sensor.cli_updates') }}"
        attribute_templates:
          installed_version: "{{ state_attr('sensor.cli_updates', 'installed_version') }}"
          latest_version: "{{ state_attr('sensor.cli_updates', 'latest_version') }}"
      updater_multicast:
        friendly_name: Multicast
        device_class: problem
        value_template: "{{ states('sensor.multicast_updates') }}"
        attribute_templates:
          installed_version: "{{ state_attr('sensor.multicast_updates', 'installed_version') }}"
          latest_version: "{{ state_attr('sensor.multicast_updates', 'latest_version') }}"
      updater_observer:
        friendly_name: Observer
        device_class: problem
        value_template: "{{ states('sensor.observer_updates') }}"
        attribute_templates:
          installed_version: "{{ state_attr('sensor.observer_updates', 'installed_version') }}"
          latest_version: "{{ state_attr('sensor.observer_updates', 'latest_version') }}"

sensor:
  - platform: command_line
    name: core_updates
    command: 'curl http://supervisor/core/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"latest_version":.data.version_latest,"installed_version":.data.version,"update_available":.data.update_available}'''
    value_template: "{{ value_json.update_available }}"
    scan_interval: 600
    json_attributes:
      - update_available
      - latest_version
      - installed_version

  - platform: command_line
    name: supervisor_updates
    command: 'curl http://supervisor/supervisor/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"latest_version":.data.version_latest,"installed_version":.data.version,"update_available":.data.update_available}'''
    value_template: "{{ value_json.update_available }}"
    scan_interval: 600
    json_attributes:
      - update_available
      - latest_version
      - installed_version

  - platform: command_line
    name: os_updates
    command: 'curl http://supervisor/os/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"latest_version":.data.version_latest,"installed_version":.data.version,"update_available":.data.update_available}'''
    value_template: "{{ value_json.update_available }}"
    scan_interval: 600
    json_attributes:
      - update_available
      - latest_version
      - installed_version

  - platform: command_line
    name: addons_updates
    command: 'curl http://supervisor/addons -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"addons":[.data.addons[] | select(.update_available)]}'''
    value_template: "{{ value_json.addons | length }}"
    scan_interval: 600
    unit_of_measurement: pending update(s)
    json_attributes:
      - addons

  - platform: command_line
    name: audio_updates
    command: 'curl http://supervisor/audio/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"latest_version":.data.version_latest,"installed_version":.data.version,"update_available":.data.update_available}'''
    value_template: "{{ value_json.update_available }}"
    json_attributes:
      - update_available
      - latest_version
      - installed_version
  - platform: command_line
    name: dns_updates
    command: 'curl http://supervisor/dns/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"latest_version":.data.version_latest,"installed_version":.data.version,"update_available":.data.update_available}'''
    value_template: "{{ value_json.update_available }}"
    json_attributes:
      - update_available
      - latest_version
      - installed_version
  - platform: command_line
    name: cli_updates
    command: 'curl http://supervisor/cli/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"latest_version":.data.version_latest,"installed_version":.data.version,"update_available":.data.update_available}'''
    value_template: "{{ value_json.update_available }}"
    json_attributes:
      - update_available
      - latest_version
      - installed_version
  - platform: command_line
    name: multicast_updates
    command: 'curl http://supervisor/multicast/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"latest_version":.data.version_latest,"installed_version":.data.version,"update_available":.data.update_available}'''
    value_template: "{{ value_json.update_available }}"
    json_attributes:
      - update_available
      - latest_version
      - installed_version
  - platform: command_line
    name: observer_updates
    command: 'curl http://supervisor/observer/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"latest_version":.data.version_latest,"installed_version":.data.version,"update_available":.data.update_available}'''
    value_template: "{{ value_json.update_available }}"
    json_attributes:
      - update_available
      - latest_version
      - installed_version

input_text:
  base_url:
    name: Home Assistant URL
    initial: !secret external_url

group:
  updaters:
    name: Updates
    entities:
      - binary_sensor.updater_core
      - binary_sensor.updater_supervisor
      - binary_sensor.updater_os
      - binary_sensor.updater_addons
      - binary_sensor.updater_hacs
