---
sensor:
  - platform: template
    sensors:
      thomas_status:
        value_template: >-
          {% if is_state('device_tracker.tbiphone11', 'home') %}
            Home
          {% elif is_state('device_tracker.tbiphone11', 'trc') %}
            Work
          {% else %}
            Away
          {% endif %}
        icon_template: >-
          {% if is_state('device_tracker.tbiphone11', 'home') %}
            mdi:home
          {% elif is_state('device_tracker.tbiphone11', 'trc') %}
            mdi:office-building
          {% else %}
            mdi:car
          {% endif %}
        friendly_name: "Thomas"
        entity_picture_template: /local/avatar_thomas.jpg
