---
sensor:
  - platform: unifigateway
    host: !secret unifi_ipaddress
    port: 443
    username: !secret unifi_username
    password: !secret unifi_password
    version: "UDMP-unifiOS"
    monitored_conditions:
      - vpn
      - lan
      - wan
      - www
      - wlan
      - alerts
      - firmware

  # - platform: my_unifi
  #   name: my_unifi
  #   region: default
  #   url: https://192.168.1.1
  #   username: !secret unifi_username
  #   password: !secret unifi_password

  - platform: template
    sensors:
      unifi_gateway_wan_cpu:
        friendly_name: "CPU"
        unit_of_measurement: "%"
        icon_template: mdi:cpu-64-bit
        value_template: "{{ states.sensor.unifi_gateway_wan.attributes['gw_system-stats']['cpu'] }}"
      unifi_gateway_wan_mem:
        friendly_name: "Memory"
        unit_of_measurement: "%"
        icon_template: mdi:memory
        value_template: "{{ states.sensor.unifi_gateway_wan.attributes['gw_system-stats']['mem'] }}"
      unifi_gateway_www_xput_down:
        friendly_name: "USG Speedtest Download"
        unit_of_measurement: Mbps
        icon_template: "mdi:progress-download"
        value_template: "{{ states.sensor.unifi_gateway_www.attributes.xput_down }}"
      unifi_gateway_www_xput_up:
        friendly_name: "USG Speedtest Upload"
        unit_of_measurement: Mbps
        icon_template: "mdi:progress-upload"
        value_template: "{{ states.sensor.unifi_gateway_www.attributes.xput_up }}"
      unifi_gateway_www_speedtest_ping:
        friendly_name: "USG Speedtest Ping"
        unit_of_measurement: ms
        icon_template: "mdi:progress-clock"
        value_template: "{{ states.sensor.unifi_gateway_www.attributes.speedtest_ping }}"
      unifi_gateway_wlan_num_user:
        friendly_name: "WiFi Users"
        icon_template: mdi:wifi
        value_template: "{{ states.sensor.unifi_gateway_wlan.attributes.num_user }}"
      unifi_gateway_lan_num_user:
        friendly_name: "Wired Users"
        icon_template: mdi:lan
        value_template: "{{ states.sensor.unifi_gateway_lan.attributes.num_user }}"
      unifi_gateway_wan_download:
        friendly_name: "WAN Download"
        unit_of_measurement: Kbps
        value_template: "{{ (states.sensor.unifi_gateway_wan.attributes['rx_bytes-r'] / 1024) | int }}"
      unifi_gateway_lan_sw:
        friendly_name: "LAN Switch Count"
        value_template: "{{ states.sensor.unifi_gateway_lan.attributes['num_sw'] }}"
        unit_of_measurement: Switches
        icon_template: mdi:lan
      unifi_gateway_wlan_ap:
        friendly_name: "WiFi AP Count"
        value_template: "{{ states.sensor.unifi_gateway_wlan.attributes['num_ap'] }}"
        unit_of_measurement: APs
        icon_template: mdi:wifi
      unifi_gateway_wan_ip:
        friendly_name: "WAN IP"
        icon_template: mdi:wan
        value_template: "{{ states.sensor.unifi_gateway_wan.attributes.wan_ip }}"
      unifi_gateway_www_uptime:
        friendly_name: "Internet Uptime"
        icon_template: mdi:av-timer
        value_template: >
          {% set time = (states.sensor.unifi_gateway_wan.attributes['gw_system-stats']['uptime'] | int) | int %}
          {% set minutes = ((time % 3600) / 60) | int %}
          {% set hours = ((time % 86400) / 3600) | int %}
          {% set days = (time / 86400) | int %}

          {%- if time < 60 -%}
            Less than a minute
            {%- else -%}
            {%- if days > 0 -%}
              {{ days }}d
            {%- endif -%}
            {%- if hours > 0 -%}
              {%- if days > 0 -%}
                {{ ' ' }}
              {%- endif -%}
              {{ hours }}h
             {%- endif -%}
             {%- if minutes > 0 -%}
               {%- if days > 0 or hours > 0 -%}
                 {{ ' ' }}
               {%- endif -%}
               {{ minutes }}m
             {%- endif -%}
           {%- endif -%}
      unifi_gateway_firmware:
        friendly_name: "UDM-Firmware Version"
        value_template: "{{ states.sensor.unifi_gateway_wan.attributes.gw_version }}"
        icon_template: mdi:counter
