---
sensor:
  - platform: template
    sensors:
      untappd_badge:
        value_template: "{{ states.sensor.untappd_last_badge_bacco007.attributes.badge }} (Level {{ states.sensor.untappd_last_badge_bacco007.attributes.level }})"

      untappd_beer:
        value_template: "{{ states.sensor.untappd_last_check_in_bacco007.attributes.beer }} ({{ states.sensor.untappd_last_check_in_bacco007.attributes.abv }})"

      untappd_followings:
        value_template: "{{ states.sensor.untappd_last_check_in_bacco007.attributes.followings }}"
        entity_picture_template: "https://www.shareicon.net/data/32x32/2016/09/23/833751_people_512x512.png"

      untappd_checked:
        value_template: "{{ states.sensor.untappd_last_check_in_bacco007.attributes.checkins }}"
        entity_picture_template: "https://www.shareicon.net/data/128x128/2015/05/30/46550_check_32x32.png"

      untappd_total_beers:
        value_template: "{{ states.sensor.untappd_last_check_in_bacco007.attributes.total_beers }}"
        entity_picture_template: "https://www.shareicon.net/data/32x32/2016/09/26/834858_drink_512x512.png"

      untappd_total_badges:
        value_template: "{{ states.sensor.untappd_last_check_in_bacco007.attributes.total_badges }}"
        entity_picture_template: "https://www.shareicon.net/data/32x32/2016/07/10/794103_miscellaneous_512x512.png"
