esphome:
  name: testnodemcu

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Za9vdvbcI4Iy+7zyFr2SD95Emxb2mRWt15ge3SqtT3U="

ota:
  password: "320ebb5684f344e2d264921a687472a7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Testnodemcu Fallback Hotspot"
    password: "v6aVaGOyc4iw"

captive_portal:
    